### ISSUE TITLE
Include video length on Pocket video feed items

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1046]
### Why/User Benefit/User Problem
via sebastian:
> Do we know the length of the videos? I would like to know how long they are before I start them ("Is this something quick I can watch now or does this take an hour?")

**Comment by bbinto** [comment]
@Sdaswani to reach out to Kenny

**Comment by Sdaswani** [comment]
https://mozilla.slack.com/archives/C8P1Z6JSZ/p1536086992000100

**Comment by mkoidin** [comment]
We have video length for most of our Youtube videos.

Looks like we store it in seconds - I assume that would be okay and you would convert to however you want to display on your end of things?

My main parser engineer is out this week - I would like to just confirm with him next week I’m not missing anything, but otherwise can create a ticket around this and work to get it in.

If we do not have a length, we will not include that field in the response - that make sense?

**Comment by Sdaswani** [comment]
@mkoidin thanks - please let us know when seconds is available from the API. @bbinto maybe we can get this in 3.0 but we may need some new UI @aminalhazwani.

**Comment by aminalhazwani** [comment]
I am going to assign myself as a reminder 🙂

**Comment by mcomella** [comment]
Dupe #2299.
