### ISSUE TITLE
SUMO article for FFTV v3.0

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1048]
Milestones:
- [Sprint 0/backlog](https://github.com/mozilla-mobile/firefox-tv/milestone/13)
- Sprint 1 is empty
- [Sprint 2](https://github.com/mozilla-mobile/firefox-tv/milestone/21)
- [Sprint 3](https://github.com/mozilla-mobile/firefox-tv/milestone/22)

@jonisavage btw, we've started keeping [a CHANGELOG](https://github.com/mozilla-mobile/firefox-tv/blob/master/CHANGELOG.md) for major user-facing changes: hopefully it's helpful to you! Unfortunately, we don't have v3.0 entries there yet but hopefully we'll catch up soon.

**Comment by bbinto** [comment]
@jonisavage would you mind providing us with an update? Thanks

**Comment by jonisavage** [comment]
I apologize for the delay. As far as I can tell, we've documented the user-facing features for FFTV 3.0. Here's what we have:
https://support.mozilla.org/en-US/kb/save-or-bookmark-and-remove-links-your-home-screen
https://support.mozilla.org/en-US/kb/using-voice-commands-firefox-amazon-fire-tv
https://support.mozilla.org/en-US/kb/return-your-firefox-fire-tv-home-screen

Are we missing anything?

**Comment by liuche** [comment]
Sent @Sdaswani a LAT candidate so expect a LAT build soon!

**Comment by Sdaswani** [comment]
FYI @jonisavage has the latest LAT now, @dnarcese can you help with her questions?

**Comment by dnarcese** [comment]
@jonisavage 

- The images of the pin button on [https://support.mozilla.org/en-US/kb/save-or-bookmark-and-remove-links-your-home-screen](https://support.mozilla.org/en-US/kb/save-or-bookmark-and-remove-links-your-home-screen ) have since changed. The orientation of the pin is now flipped, the background colour is different, and the background will be black instead of blue when selected.
- The images of the turbo button on [https://support.mozilla.org/en-US/kb/turn-turbo-mode-or-firefox-fire-tv]( https://support.mozilla.org/en-US/kb/turn-turbo-mode-or-firefox-fire-tv) also need to be updated, and when it is selected the rocket will be white instead of black.
- The image of the settings button on [https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox-fire-tv](https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox-fire-tv) needs to be updated.

That's it, thanks!

**Comment by mcomella** [comment]
@jonisavage On my test account, I was unable to download the update until I
clicked the "Download update" link in the "Live App Testing" message in my
email. Have you seen an email like this? Maybe it went to your spam?

**Comment by jonisavage** [comment]
Thanks for the clarification, Daniela, and for the screenshots, Michael. I've updated the articles so they're ready.

**Comment by Sdaswani** [comment]
Thanks @jonisavage !
