### ISSUE TITLE
Going to firefox:home shows white screen, makes app unusuable

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#1155]
## Steps to reproduce
Open Firefox app
go to URL bar, and either type firefox:home or press Enter if the bar is prepopulated with 'firefox:home' text

### Expected behavior
Shows main tiles page

### Actual behavior
White screen, app becomes unusuable. need to force stop

### Device information

* Fire TV device: Basic TV stick
* Firefox version: master branch

**Comment by liuche** [comment]
Hmm, so this is a regression caused by a few things.
#1134 was a result of #1081, and it's a workaround for the specific case on the home screen, but then it causes this bug.

I remember #1081 working before, and going back to an older build, when we hadn't fully integrated Pocket (975a09e2115eb), we don't have either #1081 or #1134.

I think the solution here is to back out #1134 and find the real fix for #1081, which will also fix this bug.

**Comment by Baron-Severin** [comment]
@liuche I agree that that's what we need to do.  I've worked out why this is happening and filed an issue on A-C: https://github.com/mozilla-mobile/android-components/issues/825

**Comment by Baron-Severin** [comment]
I've done some more research on this.  I'm not sure when it was introduced, but it is reproducible at at least as far back as 1884ae2cfe48cc359b13486cf885438221bd5b49 (Aug 16).  So it looks like this isn't related to #1134, and we'll need to work out the root cause.
