### ISSUE TITLE
YouTube Casting

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#1284]
### Why/User Benefit/User Problem

I want to play YouTube videos on my big screen TV, but navigating the YouTube site with the FireTV controller is difficult and takes a lot longer than on my phone. I want to be able to play videos I find on my phone through my FireTV.

### What / Requirements

Allow users to play a YouTube video on their phone through the FireTV

### Acceptance Criteria (how do I know when I’m done?)

- User can play a youtube video they’ve found on their phone through the Fire TV
- User is informed on their Fire TV when a video is sent there from Youtube (built in)
- Add videos to the queue to watch next
- Video can be controlled through the phone or Fire TV remote
- Tracking is in place for usage of the feature

### Antivision

- This does not include onboarding or hints for the user. That will be logged as a separate issue.

### Notes on Implemenations

The YouTube mobile app has a Fling feature where you can select mobile videos on your phone and playback on your Fire TV. This is a top feature request from customers.

Step 1: Make the application discoverable

    Add an XML resource named whisperplay.xml. This file resides directly in the folder
    app/src/main/res/xml.
    Add the following entry in the AndroidManifest.xml file. This entry must be a child of the
    application tag:

Step 2: Handle the DIAL parameters

    Since we are working with the SafeIntent as opposed to the raw intent, add code in the
    SafeIntent to be able to parse out the DIAL parameters.

public void setDialParams(String dialParams) {
intent.setAction(Intent.ACTION_VIEW);
intent.setData(android.net.Uri.parse("https://www.youtube.com/tv?" + dialParams));
}

    Add code in the SessionManager class inside the method createSessionFromIntent to parse out
    the dial parameters (TAG can be set to any string for ease of finding log entries):

String dialParamsKey = "com.amazon.extra.DIAL_PARAM";
String dialParams = intent.getStringExtra(dialParamsKey);

if (dialParams != null && !"".equals(dialParams)) {
android.util.Log.i(TAG, "dialParams = " + dialParams);
intent.setDialParams(dialParams);
}
else {
android.util.Log.i(TAG, "NO dial params");
}

Step 3: Navigate to the appropriate URL
When a Youtube video is cast to the application, a pairing code is passed inside of the intent. The name
of the parameter inside of the intent was com.amazon.extra.DIAL_PARAM. Pass the parameter into
the Youtube.com/tv website as a GET parameter. In the step above, the method setDialParams modified
the intent to open the appropriate URL if a DIAL intent was sent to the browser.
The final URL to navigate to will be:
"https://www.youtube.com/tv?" + dialParams

**Comment by liuche** [comment]
Here are the Amazon dev docs: https://developer.amazon.com/docs/fire-tv/dial-integration.html

**Comment by aminalhazwani** [comment]
⚠️ **IN PROGRESS** ⚠️ 

I was able to cast from the YouTube mobile and tablet app to the Fire TV via Silk. I wasn't able to cast from Laptop/Chrome to the Fire TV. For now we could only focus on casting from mobile/tablet YouTube app to Firefox.

If you tap the cast icon in the homescreen of the YouTube app YouTube tells you that there are no videos in the queue:

<img width="2022" alt="image" src="https://user-images.githubusercontent.com/1721875/47025481-de849b00-d163-11e8-9400-2ba18b9b7ed6.png">

then Silk opens and it opens youtube.com and no video is played.

If you do the same process with a Chromecast/Android TV this message is displayed on the TV:

![img_0649](https://user-images.githubusercontent.com/1721875/47025850-8a2deb00-d164-11e8-9598-02945f811181.jpg)

First question **1) can we display a custom message if users simply tap the cast icon in the YouTube app homescreen?**

In order to notify users that this feature is available we can display a small banner/message. The banner will tell users that they can cast videos from their mobile or tablet YouTube app. They would simply have to tap the cast icon on their device and select their Fire TV from the list.

### When can we show this banner

- on launch after update/install, similarly as we do for the Turbo Mode onboarding
  - this is unfortunately not very contextual, user action-related, we might want to avoid this for such specific feature
- people launching youtube.com/tv from the homescreen
  - **question 2) does it go against our policy?**
- people typing youtube.com from the homescreen
  - **question 2) does it go against our policy?**
- people typing on youtube.com/tv (youtube uses a custom keyboard)
  - **question 2) does it go against our policy?**
- people coming from YouTube.com app
  - **question 3) do we know when external apps open Firefox?**

### How can this banner look

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/1721875/47031791-f878aa80-d170-11e8-9b2f-c417c0cc9a9e.png">

A banner that shows somewhere (see questions above), with the button focused (like the pocket onboarding) ready to be dismissed.

Worth considering: if we display the message not on website we don't need to brand the message, we simply expose the feature. But if we display the message while users browse we might want to brand it since it might be not immediately clear that the message comes from Firefox and not from the website.

### What we need to tell

cc @BrianNJones: People can access this feature via the YouTube app on their mobile or tablet device. They need to tap the cast icon and then select their Fire TV from the list of shown devices. Something like:

Text: “You can now cast YouTube videos to Firefox for Fire TV. Tap the cast icon from your YouTube mobile or tablet app.”

Button: “Ok, got it”

### What we would like to measure

- Do people cast after seeing the banner/message? 
- Others TBD

**Comment by liuche** [comment]
I've registered `org.mozilla.tv.firefox` with the DIAL registry, followed the Amazon DIAL docs (the instructions in this issue's comments seem to be missing some steps), and handle the intent and load the correct url.

However, whatever is on the Amazon DIAL docs doesn't seem to be working and I'm not seeing Firefox shown as an available casting destination. I'm wondering if I just need to wait for the DIAL registry to push the changes out[1], or if there are some additional steps I need to do.

@Sdaswani seeing if you can get some more information.

[1] I don't think this is the issue - I tried testing with some of the other already-registered app names, but didn't see the casting protocol show up either.

**Comment by Sdaswani** [comment]
@liuche I'm happy to go to Amazon for help on this, but they seemed to have it working previously, so I want to make sure we didn't miss something from their code sample before I arrange a call. Let me know.

**Comment by Sdaswani** [comment]
Thanks for flagging @liuche!

**Comment by Sdaswani** [comment]
Yay 😃

**Comment by Sdaswani** [comment]
@psymoon can you detail the disconnect case that works in Silk but doesn't work in Firefox?
