### ISSUE TITLE
[1364] #11: Pocket tile + screen loading/error state

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1387]
It's hard for QA to manually test that all the error states of Pocket are not working correctly so we should write an automated test with dummy data to test for us. In particular, we should verify:
- Loading state appears
- Loading state transitions to error (or success) correctly
- Error states look correct
- Try again button works correctly

Notes:
- We may want to wait until Pocket moves to channels to handle this.
- This may already be covered well enough by the screenshot tests

**Comment by mcomella** [comment]
@Baron-Severin Should this be duped to #1045 or is there going to be more covered in this issue?

**Comment by Baron-Severin** [comment]
This looks more in depth, so I think they should stay separate.  The other one is a smoke test that just makes sure that the happy path (data loads properly, clicking on it takes you to the fragment, selecting a video loads the URL) works properly.

**Comment by dnarcese** [comment]
The best way to do this would be to mock the pocket endpoint and make it so that on first hit it returns an error state and on the next hit it returns a success state. This would require the serviceLocator to be substituted per individual test, so that each test can change the dependencies it needs.

**Comment by Baron-Severin** [comment]
@dnarcese I would normally agree, but we previously set up some code to support this kind of testing.  Any Espresso test should be able to push out mocked `PocketRepo` state via `FirefoxTestApplication#pushPocketRepoState`, and it'll immediately flow out through the app.  So that part of the test should be pretty easy.

**Comment by dnarcese** [comment]
@Baron-Severin I tried it that way, but I think the problem was that Try Again did not function properly. `pushPocketRepoState` created another repo state that Try Again could not update. So clicking Try Again was not updating the UI.

**Comment by Baron-Severin** [comment]
@dnarcese Sounds like the code I wrote to set up tests isn't as flexible as it should be.  Is there a WIP branch with these changes where I can try to improve on it?

**Comment by dnarcese** [comment]
@Baron-Severin https://github.com/dnarcese/firefox-tv/commit/4a8fcdec1271e1c4162c7bf1c327eb67554d658b

**Comment by Baron-Severin** [comment]
@dnarcese just an update, I'm still working on that change.  There are a few things that make it difficult, I opened up https://github.com/mozilla-mobile/firefox-tv/issues/1651 and included more details there.

**Comment by athomasmoz** [comment]
@mcomella is this still relevant with the new way we load pocket videos?

**Comment by mcomella** [comment]
Nope, thanks for catching this.
