### ISSUE TITLE
ProgressBar lingers after page load

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1442]
### Why/User Benefit/User Problem
We are currently displaying the ProgressBar for three seconds after a page load completes.  Based on personal, informal testing, shortening this seems to have a massive impact on perceived performance.  I think we should consider tweaking this number.

Current (3 second pause)
![progress-3](https://user-images.githubusercontent.com/13170306/47878804-5f869800-dddc-11e8-8408-5f26aea3bf9c.gif)

2 second pause
![progress-2](https://user-images.githubusercontent.com/13170306/47878833-6f05e100-dddc-11e8-8989-a605ca2c170c.gif)

1 second pause
![progress-1](https://user-images.githubusercontent.com/13170306/47878840-7331fe80-dddc-11e8-8634-78504e1e1cee.gif)

We can do any number in between these as well, these are just good examples.

**Comment by liuche** [comment]
@aminalhazwani since this is tiny, we'd like to do this in the next sprint because it's literally just changing a "how long we want to delay"

Here's the line to change, if you want to try some values (and you can even make a PR if you want :P)
https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/main/java/org/mozilla/tv/firefox/webrender/FirefoxProgressBar.kt#L25
