### ISSUE TITLE
YouTube toolbar back visits redirects

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-tv#1543]
## Steps to reproduce
1. Click on Google search tile
2. Open overlay and click on YouTube tile
3. Click back several times with overlay back button
4. Observe url bar
### Expected behavior
- If watching video- goes back to YouTube homescreen, then to Google
- If on YouTube homescreen- goes back to Google
### Actual behavior
Each back click visits a YT redirect link which does not affect the displayed page. After 5 back clicks, Google is shown.
### Device information

* Fire TV device: 4k
* Firefox version: 3.1

**Comment by athomasmoz** [comment]
@psymoon @dnarcese Check out possibel solutions
@aminalhazwani can you confirm the desired behaviour here?

**Comment by dnarcese** [comment]
a-c needs to expose whether a page load is a redirect so that we can handle back behaviour differently.
Link to issue -> https://github.com/mozilla-mobile/android-components/issues/1493

**Comment by aminalhazwani** [comment]
>  @aminalhazwani can you confirm the desired behaviour here?

Yes, confirmed. 

As a side note the same happens on Desktop if we open youtube.com/tv. But it doesn't happen for other website which have a redirect.

**Comment by mcomella** [comment]
afaict, these aren't redirect links: youtube.com/tv is actually broken. It doesn't handle back button presses beyond changing the URL. You can reproduce this behavior on desktop:
- Open youtube.com/tv on desktop
- Click a video
- Press back in toolbar

Expected: go back to previous youtube page
Actual: content only changes when moving to previous

**Comment by mcomella** [comment]
I think this can be closed as WORKSFORME (unless we wanted to reach out to youtube about the problem).

**Comment by mcomella** [comment]
To be explicit about what youtube is doing, I think they're using the [HTML 5 history API](https://developer.mozilla.org/en-US/docs/Web/API/History_API#Adding_and_modifying_history_entries) which lets a website update the URL and add events to the back/forward toolbar back stack _without reloading the page_ (i.e. letting them dynamically fetch and modify the content with javascript). This behavior is visible on youtube (notice the progress bar embedded in the page when loading videos) and github (same: notice the progress bar after clicking certain things). Unfortunately, *they are not handling the back stack pop event* so nothing happens when back is pressed.
