### ISSUE TITLE
Grey screen on WebView after Settings

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-tv#1559]
## Steps to reproduce
1. Click Google search tile
2. Open overlay and click Settings
3. Click back on remote
4. Click menu button
### Expected behavior
Google search should appear.
### Actual behavior
Grey screen with frozen progress bar is shown. If you scroll down, Google search is shown but the progress bar is still frozen on screen.
### Device information

* Fire TV device: 4k
* Firefox version: 3.1

**Comment by Baron-Severin** [comment]
I encountered something that looks very similar.

## Steps to reproduce
- Open YouTube (not reproducible on any other site)
- Press menu button to open overlay
- Press home button
- Reopen FFTV
- Press menu button to close overlay

### Expected behavior
- WebView is visible

### Actual behavior
- Grey screen is displayed (attached below)
- Hitting select or any D-pad direction fixes the problem

### Device information
* Fire TV device: Cube
* Latest affected Firefox version: 6df28612e213679775aed4529251e41fb3a24774
* Earliest affected Firefox version: ?

(screenshot of actual behavior)
![grey-screen](https://user-images.githubusercontent.com/13170306/53039826-e2d40400-3434-11e9-9ad1-45290273beae.png)

**Comment by athomasmoz** [comment]
Can I close this one? I can't reproduce. And from the sounds of #1940 that's because it's been fixed in a hacky way, and there's already 1940 to improve the solution

**Comment by psymoon** [comment]
@abodea confirmed this is no longer reproducible
