### ISSUE TITLE
Cursor disappears after history is cleared, and back button is pressed from URL page

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#1590]
## Steps to reproduce
- Open Google.com 
- Press back button to go to the tile view
- Go to settings, and clear history
- Enter URL on the URL bar to open google.com again
- Press back button

### Expected behavior
- Tile view should be shown, with selected element highlighted

### Actual behavior
- There is no highlight on the tile view, clicking menu button shows the highlight on the back button, but it cannot be moved.  Clicking the back button shows grey screen
### Device information

* Fire TV device: Cube
* Firefox version: 3.1.3

**Comment by AaronMT** [comment]
Current work-around is to use the device `menu` button to return to the home-screen.

**Comment by liuche** [comment]
Looking at this, it seems really similar to #1592, because we're not handling focus correctly when returning to the homepage after history is cleared. (Also see @dnarcese's [comment](https://github.com/mozilla-mobile/firefox-tv/issues/1589#issuecomment-448703643) in #1589, which probably isn't related but could be confusing the overlayVisibility check if we're not "on" the correct ABOUT_HOME url).

**Comment by npark-mozilla** [comment]
FYI, this does not repro on 2.1.2
