### ISSUE TITLE
Integrate Glean SDK Trial

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1652]
### Why/User Benefit/User Problem
Glean is the path forward for mobile telemetry SDKs at Mozilla so we should use it to reduce the maintenance burden of using our own telemetry SDK owned by the product teams. This should be more reliable and more easy to test than our existing solution.

### What / Requirements

- Review PR from Glean team
- Create SLA (agreement with glean team on post-production support)

### Acceptance Criteria (how do I know when I’m done?)

- The glean trial is set up in our codebase
- SLA with Glean team for support post-launch

---

The Glean integration is a ways off but this bug can be used to track concerns before we get there.

Instructions (Step 1 and 3):
https://github.com/mozilla-mobile/android-components/blob/master/components/service/glean/README.md#usage

See also FFES: https://github.com/mozilla-mobile/firefox-echo-show/issues/171

**Comment by athomasmoz** [comment]
Focus for Glean right now is Fenix. We will pick this back up later this year.

**Comment by bbinto** [comment]
Talked to @athomasmoz on Monday, this is back, and ideally to be done by end of March. Please reach out to Frank and Georg for more info.

**Comment by athomasmoz** [comment]
Note on timing from Georg:
We could schedule the integration work earliest April 1, targeting an April 8 or later release/shipping date (we will have stabilized the core Glean functionality until then).
The latest date i see is May 13, that would still gives us a bit of time to react to findings if needed.

**Comment by athomasmoz** [comment]
Implementation details: https://github.com/mozilla-mobile/android-components/blob/master/components/service/glean/README.md#usage

**Comment by devinreams** [comment]
PR created and ready for review: https://github.com/mozilla-mobile/firefox-tv/pull/2158

**Comment by devinreams** [comment]
@travis79 thanks for checking in again. We have a code freeze tomorrow (Thursday) and we aim to prioritize this as part of the beginning of the next release/sprint so as to help test and identify any potential issues or regressions (as opposed to right before release prep).

Please let us know if you have any other questions.

**Comment by liuche** [comment]
I'll take on sending an email to Travis about expectations on our side, and then we can merge this.

**Comment by liuche** [comment]
Just copying the expectations for bugfixes/support that we discussed w/ the Glean team here:

- Support in #glean channel if we run into any problems (Alessio, Travis, Mike are on hand to help!)
- If there are bugs on master, someone from the Glean team will own figuring out those problems and opening a PR to fix it (code freeze for us is 5/22)
- If there are bugs in production, a 24-hour period of time to get a fix in so we can push a dot-release - otherwise we’d back out the PR (if there is heavy crashing that we didn’t catch in QA, we’d back out immediately)

Just to be clear, this is just a contingency plan! We don’t expect anything to go wrong like this 🙂.
