### ISSUE TITLE
Setup A/A Test with Fretboard (release and verify)

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#1675]
### Why/User Benefit/User Problem

As a PM, I want to see the difference in metrics for 2 test groups created with Fretboard, so that I can measure the impact of new features using A/B tests

### What / Requirements

* A/A test run with Fretboard, using a 50/50 split
* Dashboard set up to monitor results (data science request https://bugzilla.mozilla.org/show_bug.cgi?id=1520033 )

### Acceptance Criteria (how do I know when I’m done?)

* We have confirmed that Fretboard is set up properly
* We have confirmed that we can see a comparison in metrics for a split test
* We have confirmed that we can change percentages allocated to each variate (confirm audience size changes appropriately with it)

**Comment by Sdaswani** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1523416 is the request to get any needed help from data science.

**Comment by dnarcese** [comment]
The A/A test is created on server - waiting on the dashboard to verify setup.

**Comment by liuche** [comment]
Removing label bc this doesn't have any eng work.

**Comment by liuche** [comment]
@mmccorks we've made a LAT build for this, so this is "pre-released" with a release build - let us know if you're seeing anything. If not, we should figure out what we need to do next.

**Comment by Baron-Severin** [comment]
@athomasmoz Just a note, we have had somewhere around 3k people on a version with the A/A test today, and 402 of them were not bucketed into either A or B.  (Note that this is not a crash, and does not adversely affect the client)

https://sentry.prod.mozaws.net/operations/firefox-tv/issues/5201045/?query=is:unresolved

@psymoon please correct me if I'm wrong, but I believe Fretboard makes a request on startup, but uses the most recently persisted value instead of blocking on its return?  Could these be people who encounter the test before their first request has completed?  If so we should be careful to always handle that case.

**Comment by psymoon** [comment]
@Baron-Severin 

You're correct. We could use a better sentry log for this, however.

**Comment by athomasmoz** [comment]
Completed https://sql.telemetry.mozilla.org/dashboard/firetv-aa-test#159522
