### ISSUE TITLE
ScreenController Inconsistent state assertion on 3.2

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#1691]
ScreenController Inconsistent state, expected NAVIGATION_OVERLAY, got WEB_RENDER 

https://sentry.prod.mozaws.net/share/issue/074800e7d1f7460ea3be3412edc9194e/

**Comment by Baron-Severin** [comment]
Note that this is not actually crashing, it logs an exception to Sentry but does not throw.

This occurs when a user clears data.  This effectively changes the currently active screen to the navigation overlay, but does not update state in `ScreenController`.  This causes actual and percieved state to be out of sync, triggering a report to Sentry.  This should be fixed as it could lead to hard to track down fragment transaction bugs.

**Comment by Baron-Severin** [comment]
From the commit message of the fix:

RCA:
When clearing data, the displayed screen was changed to NavigationOverlayFragment, however the ScreenController did not actually update its currentActiveScreen value. This caused a disconnect between expected and actual current state. At this time, no user impact has been noticed, but there could be strange transaction bugs related to this.
    
Fix:
Setting up fragments for a new session is guaranteed to display the NavigationOverlayFragment, so instead of asserting that state, the method now sets it.
    
Regressions:
To avoid regressions, we should work out a system for assertions that crash on debug and report to Sentry silently on release, then periodically assert app state throughout ScreenController to guarantee that no similar situations exist in the app. Opened https://github.com/mozilla-mobile/firefox-tv/issues/1693
