### ISSUE TITLE
Clearing data while video playback crashes app

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#1720]
## Steps to reproduce
- Go to 680news.com (or youtube), open a video for fullscreen playback
- Click menu button, go to settings, and clear data

### Expected behavior
- Data cleared, app returns to Settings

### Actual behavior
- App crashes
### Device information

* Fire TV device: Fire TV basic
* Firefox version: 3.3.0 LAT

**Comment by psymoon** [comment]
My investigation thus far:
- This is only happening in release builds (not in debug)
- This is a regression from 3.2.5 (AC37 + Refactor merge)
- There's a webview leak happening with clear cache and video playback (fix in https://github.com/mozilla-mobile/firefox-tv/pull/1726)
- The major related behavioural difference between 3.2.5 and 3.3.0 LAT is the video keeps playing in the background (due to show/hide)

**Comment by liuche** [comment]
I was trying to find the Sentry log for this, so we could be a little clearer on what was happening, but for some reason I'm not seeing any crashes from 3.3.0-LAT1 🤔

**Comment by AaronMT** [comment]
Able to crash doing this while in video playback on YouTube on 3.3.0

**Comment by liuche** [comment]
To handle the 10% case, let's try pausing the videos when switching to the Settings fragment.

**Comment by mcomella** [comment]
We have code in media session to pause all the videos:
```kotlin
webView?.evalJS("document.querySelectorAll('video').forEach(v => v.pause());")
```

We should extract this into a function and call it from both places.
