### ISSUE TITLE
A/B Test for Pinning icon

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1784]
We've seen some confusion in user reports that "there is no way to bookmark sites". We have this feature, but let's consider doing an A/B test using different iconography in case people just don't recognize the pin icon.

This could be as simple as using a "star" icon instead (and going to tag @brampitoyo for more context - other things could involve changing strings, but that would make this much more of a heavy-weight test).

Candidate for our first A/B test.

**Comment by athomasmoz** [comment]
@brampitoyo Is this something you think we should try? Or do you have other alternatives to help users discover pinning?

**Comment by brampitoyo** [comment]
@athomasmoz I would recommend implementing the hint bar, so that users who accidentally hover over the pin button will discover what it does.

In addition to this, the hint bar will also be useful for solving other problems, such as:

* Opening the home overlay using the menu button – possibly our toughest problem.
* Clarifying the function of the back button
* Editing sections on the home overlay using the menu button (and the fact that this button can change function sometimes)

If we think that the hint isn’t explicit enough (ie. it requires the user to stumble on the button, in order to discover what it does), then we should A/B string the star vs. pin icon.

**Comment by athomasmoz** [comment]
Closing in favour of the hint bar suggested above. Will re-open if we find reason to believe the icon is causing confusion
