### ISSUE TITLE
Gecko build "about:home" is broken on launch

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#1824]
## Steps to reproduce
- Select "geckoDebug" build variant
- Run and open the FFTV app

### Expected behavior
- Overlay opens with `about:home` loaded in the url bar

### Actual behavior
- Overlay opens with `data:text/html,<html></html>` in the url bar

**Comment by cpeterso** [comment]
@psymoon Does this look like bug in GV? Is GV returning `data:text/html,<html></html>` by default or failing to load FFTV's about:home page?

**Comment by liuche** [comment]
As context for @cpeterso's question, here's the bugzilla bug around this:
https://bugzilla.mozilla.org/show_bug.cgi?id=1535131

In GV, custom pages get loaded as a `data:<html>...` string where the content is in the the url. This is hard to change in GV, according to the bug, so the workaround here is to just have the "hint" show up. @athomasmoz that seems fine to me, because a user probably doesn't know what the `firefox:about` url means anyway, right?
