### ISSUE TITLE
INSTALL_FAILED_DEXOPT when trying to install geckoDebug and systemDebug

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1866]
## Impact

Build fails when trying to run in debug mode. This prevents us from being able to run tests. It's an issue with both WV and GV

## Steps to reproduce
- With Fire OS 5 (e.g. Stick gen 2?) ([device reference](https://github.com/mozilla-mobile/firefox-tv/wiki/Amazon-device-reference))
- `./gradlew assemblegeckodebug installgeckodebug`

### Expected behavior
Build installs successfully

### Actual behavior
Build fails with:
```
Execution failed for task ':app:installGeckoDebug'.
> com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: INSTALL_FAILED_DEXOPT
```

This does not happen on release builds (which proguard out some methods). This may not happen on Fire OS 6.

### Device information
* Fire TV device: Stick (gen 2?)
* Latest affected Firefox version: master: c69fcba8d1166bbb3e6c754913c216e99696c3ba
* Earliest affected Firefox version: ?

Looks like this may have started happening intermittently a week ago: #1821.

CC @Baron-Severin

**Comment by psymoon** [comment]
@mcomella Apparently this sometimes happens when lack of disk space. Proguard also significantly reduces file size so it may be something worth looking into.

**Comment by mcomella** [comment]
I think this means we're actually over the method limit on Gecko builds: Severin noticed adding RxJava sends us over on system WebView builds and Gecko adds some APIs. The release configuration will removed unused methods, putting us back under the method limit. Different versions of Android handle multi-dex differently so that explains the inconsistency on specific devices too.

The solution is likely to enable multi-dex.

**Comment by Baron-Severin** [comment]
I think I was wrong there.  When I went to enable multidexing I... noticed that it already was.  So I'm not clear on what's causing this.

**Comment by psymoon** [comment]
> I think this means we're actually over the method limit on Gecko builds: Severin noticed adding RxJava sends us over on system WebView builds and Gecko adds some APIs. The release configuration will removed unused methods, putting us back under the method limit. Different versions of Android handle multi-dex differently so that explains the inconsistency on specific devices too.
> 
> The solution is likely to enable multi-dex.

> I think I was wrong there. When I went to enable multidexing I... noticed that it already was. So I'm not clear on what's causing this.

@mcomella @Baron-Severin  yeah, we have multi-dex enabled already. We don't use `jumboMode` build flag either. Initially I thought it was us not using `MultiDexApplication` but our min SDK requirement is greater than 21 so I don't think that's necessary.

We could alternatively upgrade gradle version as well

**Comment by bdekoz** [comment]
tried TOT on the cube today, still failing. Here is the relevant part of the logcat output:

%adb logcat -c; adb logcat | grep mozilla
D/PackageManager(  975): Renaming /data/app/vmdl1568624766.tmp to /data/app/org.mozilla.tv.firefox.gecko.debug-1
D/PackageManager(  975): Resolved nativeLibraryRoot for org.mozilla.tv.firefox.gecko.debug to root=/data/app/org.mozilla.tv.firefox.gecko.debug-1/lib, isa=true
D/PackageManager(  975): Abis for package[org.mozilla.tv.firefox.gecko.debug] are primary=armeabi-v7a secondary=null
I/PackageManager(  975): Running dexopt on: /data/app/org.mozilla.tv.firefox.gecko.debug-1/base.apk pkg=org.mozilla.tv.firefox.gecko.debug isa=arm vmSafeMode=false
I/dex2oat ( 7392): /system/bin/dex2oat --zip-fd=6 --zip-location=/data/app/org.mozilla.tv.firefox.gecko.debug-1/base.apk --oat-fd=7 --oat-location=/data/dalvik-cache/arm/data@app@org.mozilla.tv.firefox.gecko.debug-1@base.apk@classes.dex --instruction-set=arm --compile-pic --instruction-set-features=div --runtime-arg -Xms64m --runtime-arg -Xmx512m --compiler-filter=space -j3 --swap-fd=9
E/dex2oat ( 7392): Verification failed on class kotlin.UByte in /data/app/org.mozilla.tv.firefox.gecko.debug-1/base.apk:classes2.dex because: Verifier rejected class kotlin.UByte due to bad method int kotlin.UByte.compareTo(java.lang.Object)
E/dex2oat ( 7392): Verification failed on class kotlin.UInt in /data/app/org.mozilla.tv.firefox.gecko.debug-1/base.apk:classes2.dex because: Verifier rejected class kotlin.UInt due to bad method int kotlin.UInt.compareTo(java.lang.Object)
E/dex2oat ( 7392): Verification failed on class kotlin.ULong in /data/app/org.mozilla.tv.firefox.gecko.debug-1/base.apk:classes2.dex because: Verifier rejected class kotlin.ULong due to bad method int kotlin.ULong.compareTo(java.lang.Object)
E/dex2oat ( 7392): Verification failed on class kotlin.UShort in /data/app/org.mozilla.tv.firefox.gecko.debug-1/base.apk:classes2.dex because: Verifier rejected class kotlin.UShort due to bad method int kotlin.UShort.compareTo(java.lang.Object)
I/DEBUG   (  155): 7->/data/dalvik-cache/arm/data@app@org.mozilla.tv.firefox.gecko.debug-1@base.apk@classes.dex
V/CrashDescriptorUtil(  975):          bed228a4  b1c68b70  /dev/ashmem/dalvik-classes2.dex extracted in memory from /data/app/org.mozilla.tv.firefox.gecko.debug-1/base.apk:classes2.dex (deleted)
E/installd(  156): DexInv: --- END '/data/app/org.mozilla.tv.firefox.gecko.debug-1/base.apk' --- status=0x000b, process failed
W/PackageManager(  975): Package couldn't be installed in /data/app/org.mozilla.tv.firefox.gecko.debug-1
I/com.android.server.pm.ExternalInstallPackageManagerCallback(  975): Installation failed for app org.mozilla.tv.firefox.gecko.debug on internal storage. Return code:-11

**Comment by npark-mozilla** [comment]
Until this bug is resolved, bitbar device test will run on 4K Stick and Cube only.

**Comment by npark-mozilla** [comment]
supposedly `android.enableD8=false` in gradle fixes the issue, but devs would need to decide whether this is a good solution.

**Comment by psymoon** [comment]
> supposedly `android.enableD8=false` in gradle fixes the issue, but devs would need to decide whether this is a good solution.

Jesup verified this worked for him with his AFTT
https://android-developers.googleblog.com/2018/04/android-studio-switching-to-d8-dexer.html

**Comment by psymoon** [comment]
Update:
Setting `android.enableD8=false` 
- works for AFTT (gen 2 stick)
- does not work for AFTA (cube): `ERROR: Java 8 language support, as requested by 'android.enableD8.desugaring= true' in your gradle.properties file, is not supported when 'android.enableD8= false'.
Affected Modules: app`

There's an apparent OS & Android API difference between the two

**Comment by psymoon** [comment]
Sounds like the new gradle version bump have resolved this issue - can @npark-mozilla confirm?

**Comment by npark-mozilla** [comment]
Yes it was working locally. @AaronMT let's work with bitbar to enable tests on Gen 2 stick.
