### ISSUE TITLE
Investigation: Voice Input not an option for search/url bar on Cube

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#1961]
## Steps to reproduce

1. Open Firefox
2. Click on URL bar

### Expected behavior

Keyboard is displayed with option to dictate term/address

### Actual behavior

Keyboard without the voice option is displayed

### Device information
* Fire TV device: Cube
* Latest affected Firefox version: 3.4-A
* Earliest affected Firefox version: ?

### Acceptance criteria

* Determine if this is something we can fix & log issue

**Comment by Baron-Severin** [comment]
Check debug vs release.  Potential whitelisting issue?

**Comment by Baron-Severin** [comment]
I attempted to reproduce this on versions:
3.4-A (unmodified)
3.4-A ('debug' removed from app ID [to avoid whitelisting problems])

And devices:
Gen 2 Stick
Cube

And I was unable to reproduce.
Keyboard - Stick
![keyboard_stick](https://user-images.githubusercontent.com/13170306/55591696-14eeac00-56eb-11e9-8afc-4c7089659c64.png)

Keyboard - Cube
![keyboard_cube](https://user-images.githubusercontent.com/13170306/55591697-15874280-56eb-11e9-9678-cd88c9664bcb.png)

@athomasmoz does this bug report come from Amazon?  Do they consider it a blocker?  I'm inclined to close this bug unless we get additional reproduction steps.

**Comment by athomasmoz** [comment]
I saw it on my cube at home actually. I'll try tonight and let you know if it's still reproducible.

**Comment by athomasmoz** [comment]
@Baron-Severin I'm able to reproduce this. Is there more info I can give you to help?

1. Open Firefox (cold-start)
2. Click on "Search or enter address" (V1)
3. Click the microphone on the remote (V2)

Expected behaviour
V1: Keyboard is displayed with hint to press microphone
V2: What I say is entered as text

Actual Behaviour:
V1: Keyboard without microphone hint is displayed
V2: My words start a Fire TV search

Device: Cube
FF Version: 3.5-A

**Comment by Baron-Severin** [comment]
So the `Press and hold [microphone] to say words and phrases` text is missing, but otherwise it's working as expected?  This is a default Fire OS keyboard, can you reproduce in Silk?  If so, I think the best we can do is report this to Amazon.  I'm curious as to why this happens on your device and not ours, but this problem doesn't strike me as super critical anyway.

They're probably going to need:
- Screenshot / picture
- From Settings -> My Fire TV -> About
  - Device Name
  - Software Version
  - Fire TV Home Version
- Consistently reproducible?

It might be good to note that it's not reproducible on the following device:
Device Name: Cube Small
Software Version: Fire OS 6.2.6.0 (NS6260/1840)
Fire TV Home Version: 6.1.3.1-004

**Comment by athomasmoz** [comment]
Confirmed its an issue on Silk as well. I'm on the same software & Fire TV home version, so not sure why it's different. If I can figure out specific criteria to reproduce, I'll report with Amazon.
