### ISSUE TITLE
A/B Test Hint Bar

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#2011]
### Why/User Benefit/User Problem

As an FFTV team member, I want to A/B test the hint bar addition, so that I can determine if it helps raise awareness of the app navigation & features

### What / Requirements

- Set up Fretboard experiment for hint bar
- Enable hint bar code in `ExperimentsProvider#shouldShowHintBar`
- Create bugzilla request for dashboard that compares
  - Menu button clicks
  - Home screen views
  - Home screen feature clicks (tiles + URL bar + icons)

### ACCEPTANCE CRITERIA

* A/B test is set up with a 50/50 split on the hint bar
* Dashboard is set up to confirm our hypothesis
* Timeline determined to follow-up and decide if we should boost to 100%

**Comment by Baron-Severin** [comment]
Blocked on https://github.com/mozilla-mobile/firefox-tv/issues/2029

**Comment by liuche** [comment]
Blocked on #1304 (@athomasmoz can you confirm?)

**Comment by athomasmoz** [comment]
@liuche @Baron-Severin My suggestion:
* Run split test with a small percentage (ie. 1%), so we can confirm the hypothesis that this brings more users to the home screen
* Hold off on releasing to larger percentage, so we can use it as a way to advertise the new home screen changes when ready

What do you think of that approach?

**Comment by Baron-Severin** [comment]
@athomasmoz that sounds good to me.  I can file a Bugzilla issue requesting a dashboard.  I think we should be tracking frequency of menu button clicks, proportion of users who have ever hit the menu button, and also general retention rate (in case it suffers with the hint bar enabled).  Does that sound good to you, or would you like anything else tracked?

**Comment by athomasmoz** [comment]
That sounds good. The only other one I had in the initial criteria above was  
> Home screen feature clicks (tiles + URL bar + icons)
Since the goal was to bring awareness to the home screen and sites outside YouTube. Althought I originally suggested tiles + URL bar + icons. I think Pocket would make more sense than icons. So it matches our query for estimating usage outside YouTube.

**Comment by Baron-Severin** [comment]
Dashboard request ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1547401

**Comment by felixlawrence** [comment]
Hi! I'm the DS summoned by your BMO ticket.

When it comes to experiments, the data science team likes to get involved _early_ - we like to be involved right from the start of experiment design, because there's lots that can go wrong in the early stages that can't be fixed later. [Here's a reference about how it's supposed to work, if you'd like to read more](https://mana.mozilla.org/wiki/display/PM/Firefox+Data+Science#FirefoxDataScience-projectworkflow)

For this experiment, we should have a meeting to discuss:
* what the proposed change is
* what behavior changes you're hoping it will drive
* what behavior changes you're worried it might drive
* what metrics you're proposing to detect these behavior changes
* what other metrics might be relevant
* your goals for the experiment (checking for unintended consequences? proving the feature is an improvement?), and your risk/uncertainty tolerance
* ideal timelines

Then I'll go and look at the existing data and run a quick power analysis to work out what % of users need to be involved. Then we can launch the experiment and start collecting data, then finally I'll analyze it (and the analysis will look quite different to the dashboard being requested here).

Can you please set up a 30 min meeting with me and anyone who sounds like they should be involved in the above? I'm on Pacific Time and my calendar is up to date.

**Comment by liuche** [comment]
Update: we have a plan for this to be tested in 4.0, along with the channels work.

**Comment by athomasmoz** [comment]
Closing ticket. All acceptance criteria completed aside from actually turning on the experiment, which is tracked in #2314
