### ISSUE TITLE
Collect number of clicks on default tiles

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2014]
### Vision

As an FFTV user, I want shortcuts to popular sites on the homescreen, so that I can discover new content & reach sites without typing in the URL

Right now, we don't know if the list of sites is what users want to see. The goal of this ticket is to track the clicks on our default tiles, so that we can determine which ones are useful to our users, and therefore, worth keeping

[brief](https://docs.google.com/document/d/1q7eVrGpje9cFpEdXSFP6B9vrDkT84yYRU9mU_-gBGz0/edit#heading=h.lzrviwt2ql63)

### Acceptance Criteria

* We can pull data to determine the number of times each default tile is clicked within a day
** Data is available through redash and a bugzilla ticket is logged to create a query
** Data is on the list to be available through Amplitude
* We cannot determine which user-added tiles are clicked or where they go

### Approach

* Send an event any time they click on one of these. The per day can be done when putting report together
* We have a number of different probes to track clicks on tiles right now. Consider how this fits in with the others
* Note implementation detail that came up from YouTube clicks: https://github.com/mozilla-mobile/firefox-tv/issues/1620#issuecomment-451973218

**Comment by liuche** [comment]
I'll talk to @suyounghong about this to get some clearer implementation details.

**Comment by liuche** [comment]
Currently we collect clicks on bundled and custom tiles, and send an *additional* event when the tile is a Youtube tile (Youtube Tile Event). This isn't particularly scalable, so we came up with an alternative:
* Add an extra to the bundled tile event, that can be something like `tilename: flickr`
* Keep the original Youtube Tile Event around for one release cycle, to sanity check that the values are the same
* File a data bugzilla ticket to make sure the Youtube tile values are the same (and to report the discrepnacy, if not)
* Remove the Youtube Tile Event, and also add in the telemetry docs a line explaining what the Youtube Tile Event was and what versions it existed in (in case Metrics needs to check the continuity for this metric, since we're migrating it to an extra)

**Comment by dnarcese** [comment]
I filed #2091 to remove the YouTube tile telemetry.
