### ISSUE TITLE
Weekly BETA Builds with AC, GV updates

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2018]
### Why/User Benefit/User Problem

As an FFTV team member, I want to release a BETA build each week so that QA and other team members can test new features & discover regressions early

### Acceptance Criteria

- [x] The first BETA build has been created
- [x] There is a release plan for future beta builds
  * Plan includes timing
  * Plan includes who's responsible
  * Plan includes updating GV and A-C
  * Plan is documented on wiki https://github.com/mozilla-mobile/firefox-tv/wiki/Releng-Checklist
  * Team is committed to following plan

**Comment by liuche** [comment]
@cpeterso how often are there new GV builds, and where is the most recent version listed? Thinking about whether we should be bumping our version every week and providing them as a LAT/private beta - I assume that anyone actually working on GV just builds with the most recent GV anyway, so this is probably more for the FFTV devs, to have the most recent version.

**Comment by cpeterso** [comment]
> how often are there new GV builds, and where is the most recent version listed?

GV builds are published on maven.mozilla.org and can be fetched automatically by Gradle:
https://maven.mozilla.org/?prefix=maven2/org/mozilla/geckoview/

New GV Nightly builds are published every morning. New GV Beta builds are published about once a week, typically on Monday. 

> Thinking about whether we should be bumping our version every week and providing them as a LAT/private beta - I assume that anyone actually working on GV+FFTV just builds with the most recent GV anyway, so this is probably more for the FFTV devs, to have the most recent version.

How often do you typically publish new LAT/private beta builds for testing? I recommend updating FFTV's GV snapshot as often as is convenient. :) Once a week is probably fine for now. Maybe update on Mondays instead of Fridays so the GV team will be around to respond to problems?

FFTV should stick with the GV Nightly channel until we have fixed all the known Gecko/GV bugs for Fire TV.

**Comment by liuche** [comment]
Currently we publish once a sprint, and that's our release candidate for QA to sign off on. However, what we test (and what we release) would be the WebView build, but it would mean the new GV version is in-tree and anyone who builds GV could do so without needing to also upgrade.

**Comment by devinreams** [comment]
Would another schedule consideration be: when to take the GV build _against_ the updated A-C (usually planned beginning of sprint) so our testing and bug reporting is as useful?

I'm not clear on the relationship between A-C and GV quite yet but wanted to throw this out if not already being considered...

**Comment by cpeterso** [comment]
> I'm not clear on the relationship between A-C and GV quite yet but wanted to throw this out if not already being considered...

AC typically targets a specific version of GV if AC depends on new GV APIs. So you might be able to update FFTV's GV version ahead of AC, but updating AC will typically also require bumping to a more recent version of GV.

**Comment by liuche** [comment]
@dnarcese since you've been working on improving our general release plan, this seems in line with that work! Could you pick this up, and also try out making a LAT release through the Amazon Developers dashboard?

In terms of the GV piece, since our LAT will be a SystemWebView, we can handle updating the GV version to a nightly (or minimally, bumping GV when AC requires it).

**Comment by dnarcese** [comment]
The first beta build (3.9-LAT1) has been submitted, closing this bug.
