### ISSUE TITLE
Address Hint Bar Blockers

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#2029]
Before the Hint Bar can be turned on, these need to be addressed.

- [x] Localization (see https://github.com/mozilla-l10n/firefoxtv-l10n/pull/21)
  - [x] Trigger screenshots once localization is done (#2087 filed)
- [ ] Accessibility (see https://github.com/mozilla-mobile/firefox-tv/issues/1907)
- [x] UX approval (see https://github.com/mozilla-mobile/firefox-tv/issues/1907)
  - [ ] change requested: don't show hint bar when playing YT video

**Comment by liuche** [comment]
All the strings have been localized on Pontoon: https://pontoon.mozilla.org/projects/firefox-for-fire-tv/

**Comment by npark-mozilla** [comment]
I was dreading this day would come :) Aaron has made a one-click solution to generate screenshots, but that was many moons ago, (curiously the need for screenshots were forgotten at one point) and now I see it needs minor updates to reflect new testrunner and UI changes. I'll create a bug for this and work on it.

cc'ing @dnarcese in case this should be a regular part of the release process.

**Comment by npark-mozilla** [comment]
https://github.com/mozilla-mobile/firefox-tv/issues/2087 for Screenshot test update

**Comment by npark-mozilla** [comment]
So it looks like the workaround https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/androidTest/java/org/mozilla/tv/firefox/ui/screenshots/SettingsTest.kt#L55 isn't switching locales on fastlane.  Only in EN-US locale the Settingspage would run, and not in other locales.

Because we need screenshot for 3.7.1, where this isn't yet incorporated, I'd need to make two separate fixes -
1. Make local changes so screenshots would work on 3.7.1 (and not check this in), including tooltip caption screenshots + screenshot generation script update
2. Make changes on master including above fix, and possibly revert the SettingsTest.kt back to Java. @liuche does it sound okay to you?

**Comment by Baron-Severin** [comment]
I've created a Fretboard experiment (`HintBar-2011`) for this feature, but it's currently set to hide for 100% of users.  We can adjust this when we're ready to test.
