### ISSUE TITLE
Add telemetry for Settings tiles

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#2044]
### Vision statement / What / Requirements
Telemetry for new settings tiles from #689 

### Impact
Usage

### Acceptance criteria
Add telemetry for 4 types of tiles + get data review

**Comment by dnarcese** [comment]
@athomasmoz Previously, we only collected telemetry for clicks on the 'toggle data collection' and 'clear data' buttons. Do we also want to add telemetry for the 'About' and 'Privacy notice' buttons here?

**Comment by athomasmoz** [comment]
Sticking to the goal of collecting only the data we need, I think we can stick with just the two we already collect. We could potentially add those ones in the future if needed.

**Comment by dnarcese** [comment]
@athomasmoz Sorry, looks like I was mistaken. We never collected clicks on the toggle data collection before, only on 'clear data'. Do we need telemetry for clicks on the toggle for sending usage data? If so, would we want to collect 
a) when the user is turning the toggle on _and_ off
b) all clicks
c) just when they turn it on
d) just when they turn it off

**Comment by athomasmoz** [comment]
Ah, let's just leave it as the 'clear data' only.

**Comment by dnarcese** [comment]
After re-thinking about this, we decided to collect clicks on each of the 4 tiles in Settings, as well as collect a total number of clicks on any Settings tile. This will follow how we collect bundled tile clicks. The reason for collecting clicks on each tile is that after moving settings to a channel, we lost data on how many clicks were on the actual 'Settings' button. So in order to know how often the Settings are used, we want to see how often the tiles are clicked.
