### ISSUE TITLE
Remove CursorViewModel#validateMotionEvent

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#2083]
After close inspection, it looks like we can remove this entire branch of code if we stop altering the event times of our touch events at all.

**Comment by mcomella** [comment]
For historical context, the original implementation (which we wrote in a week) would convert KeyEvents to MotionEvents and offset `downTime = eventTime - 100` (for an unknown reason). When the code was refactored to the `CursorController` & friends (the pre-MVVM architecture version), this historical artifact was kept. We discovered clicks were broken for GeckoView #1820 and wrote a solution with the same historical artifact.

However, it seems this historical artifact may have caused the problem because we cannot replicate the issue when directly converting the SELECT`KeyEvent` to `MotionEvent`s.
