### ISSUE TITLE
[2159] Support deleting tiles from channels

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#2166]
### Why/User Benefit/User Problem
Currently, items may only be deleted from pinned tiles.  @brampitoyo, do we plan to support removing tiles from channels, now or in the near future?

### What / Requirements
If we want to support removing tiles from other channels:
- Adjust implementation to remove from other channels
- Allow configuration of channels to allow or deny this behavior

If we do not plan to support this
- Update `registerForContextMenu(channelsContainer)` found in `NavigationOverlayFragment#onViewCreated` to only show the "Remove" popup when a pinned tile is long pressed (currently shows up on any channel tile)

**Comment by brampitoyo** [comment]
Yes. FFTV should have the ability to remove tiles from channels in the future.

(This is part of a larger work that will allow users to pin sites to specific channels and maybe even create their own channels).

Before this happens, it’s necessary for FFTV to first ship with enough tiles across enough categories. With enough tiles shipped, a need will arise to edit/remove/reorganise those tiles.

**Comment by liuche** [comment]
Refactoring to support different channels is done, and this just needs UX support to style the dialog.

This is necessary for removing tiles from channels.

**Comment by psymoon** [comment]
![screen](https://user-images.githubusercontent.com/3597594/57554035-556ec480-733e-11e9-9653-b7e8f077421f.png)

@brampitoyo This is what it currently looks like, red highlighted items are changeable (also the background). Alternatively, we can define a whole new layout.

**Comment by brampitoyo** [comment]
@psymoon 

> […] red highlighted items are changeable

Let’s use this:

**Remove metacritic from Pinned sites?**

By having the category name, this dialogue will scale when the user tries to remove a tile in other categories.

Let’s change the button title and add a new one:

**[[Remove site]]** **[[Cancel]]**

> Alternatively, we can define a whole new layout.

I’m okay with using a modal dialogue, but want to be cognizant of other dialogues we’ve already used:

![homescreen](https://user-images.githubusercontent.com/51007/57599219-1644ab80-75aa-11e9-8f7d-a084f5f777f5.png)

![homescreen](https://user-images.githubusercontent.com/51007/57599247-2d839900-75aa-11e9-93bc-8f2ba9d579f7.png)

Instead of defining a new style, I wonder whether we should reuse the text and button style of the Pocket onboarding dialogue.

Our remove tile dialogue can look like this:

![remove-pinned-site@2x](https://user-images.githubusercontent.com/51007/57599452-ce725400-75aa-11e9-804d-198fb7c1ad8d.png)

What do you think?

**Comment by psymoon** [comment]
@brampitoyo 
![screen2](https://user-images.githubusercontent.com/3597594/57647889-26e92780-7592-11e9-9826-d13b185c734f.png)

**Comment by psymoon** [comment]
Strings needed: https://github.com/mozilla-mobile/firefox-tv/blob/b53887e6d0dd3a42a9b6ff6a22a84a47910df477/app/src/main/java/org/mozilla/tv/firefox/navigationoverlay/channels/DefaultChannelAdapter.kt#L74

**Comment by brampitoyo** [comment]
@psymoon On Fire OS, the Cancel/Exit action is always to the right of the primary action button, so we did it correctly here.

![homescreen](https://user-images.githubusercontent.com/51007/57656148-b2fb5d80-762b-11e9-91a8-115681985ae9.png)
![homescreen](https://user-images.githubusercontent.com/51007/57656162-bf7fb600-762b-11e9-9790-59dbc1ff49f0.png)
![homescreen](https://user-images.githubusercontent.com/51007/57656264-0a99c900-762c-11e9-979a-42a807f1cbae.png)
![homescreen](https://user-images.githubusercontent.com/51007/57656336-3452f000-762c-11e9-9705-35f210df4a90.png)
