### ISSUE TITLE
[1630] UX requirements for home channel styling

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2209]
This bug is to get UX requirements for #2208.

### Why/User Benefit/User Problem
via #2208: if the homescreen is not delightful and usable, users won't like it. To solve these problems, we should style the homescreen to match the mocks: https://brampitoyo.github.io/people/bpitoyo/firefox-for-fire-tv/new-homescreen/i04/

### What / Requirements
For mocks, we'd like an exported mock with measurements like the mock linked above.

- [x] Get mocks for Pocket tiles: specifically, the appearance of the video description below the tiles
  - [x] Does the text scroll with the video? What happens when the video selected is the last one?
  - [x] What happens to the Pocket video text when moving focus away from the Pocket channel to a different channel? Does it remain displayed? Does it disappear?
- Get mocks for appearance of custom pinned tiles. For simplicity, decide which of these are important to fix:
  - [ ] Custom pinned tiles with screenshots (maybe broken in #2146)
  - [ ] Custom pinned tiles with placeholder letter text (note: screenshots may be broken #2146 so this may appear often)
  - These were not specified in the mocks; let's not create more work for ourselves and file a separate bug for these if they're problems
- [x] Get mocks for pinned tile channel: specifically, the text below the channel
  - Note: the current mocks do not have title text below the tiles. However, while bundled tiles and custom tiles are in the same channel, I think we'll always need to display titles because it'd look weird otherwise
  - [x] Do we want to update the appearance of our bundled tile assets or just wait until they move into categories?

#### Things (maybe) not discussed with Bram
- When all tiles in a channel are removed, the channel disappears

#### Follow-up requirements
These are requirements specified in Bram's mocks that we decided to put off to a later release. We should consider filing follow-up bugs for them when they're actionable:
- [ ] Hide tile titles (including Pocket text) when a channel is unfocused
- [ ] Dim channels that are not focused
- [ ] Change the size of the Pocket channel
- [ ] The last focused Pocket tile in a channel should be on the left side of the screen; the last focused tile in other channels should be on the right side of the screen (the latter is the current behavior)

### Acceptance Criteria (how do I know when I’m done?)
- [ ] UX provides mocks and answers questions
- [ ] Engineering okays the mocks, **thinking through edge cases**
- [ ] ? Product okays the mocks?

**Comment by mcomella** [comment]
@brampitoyo FYI: please address the issues above. If you exported more of your existing mocks, it may cover these issues.

**Comment by brampitoyo** [comment]
Hi @mcomella I’ll address this issue thoroughly next week. Stay tuned!

**Comment by brampitoyo** [comment]
@mcomella wrote:

> For mocks, we'd like an exported mock with measurements like the mock linked above.

I’ve updated and expanded the mocks above to answer all our questions. Same URL as before, to make things simple.

## 1. Pocket tiles

### Does the text scroll with the video?

Yes. **Only currently focused tile gets a title and description**. Other tiles on its side appear only as screenshots.

### What happens when the video selected is the last one?

Currently focused Pocket tile **always occupies centre position**, even when the tile selected is the last one. This is how focused item works in Amazon’s Fire OS, too.

<img width="330" src="https://user-images.githubusercontent.com/51007/57595834-7b44d500-759b-11e9-8683-8413092767b0.png"> <img width="330" src="https://user-images.githubusercontent.com/51007/57595837-826be300-759b-11e9-8a90-30710e619a13.png">

On the other hand, focused tiles on pinned sites and other category tiles occupy centre position **only up until it runs out of tile**.

<img width="330" src="https://user-images.githubusercontent.com/51007/57596038-a1b74000-759c-11e9-9383-eb733d935a43.png">  <img width="330" src="https://user-images.githubusercontent.com/51007/57596069-cd3a2a80-759c-11e9-9a05-d2a8cfa87cc5.png">

> What happens to the Pocket video text when moving focus away from the Pocket channel to a different channel? Does it remain displayed? Does it disappear?

It disappears.

As a general rule, **when a tile doesn’t have a focus ring around it, we don’t show its text**. This applies to both Pocket and Pinned sites.

#### Focus on URL bar

* ❌ Pocket tile title + description
* ❌ Pinned tile title

![Homescreen - focus URL bar@2x](https://user-images.githubusercontent.com/51007/57596160-45085500-759d-11e9-9d93-b0577542e450.png)

#### Focus on Pocket

* ✅ Pocket tile title + description (only on currently focused tile)
* ❌ Pinned tile title

![Homescreen - focus Pocket tile 1@2x](https://user-images.githubusercontent.com/51007/57596226-a7f9ec00-759d-11e9-9f15-7ff86c19454a.png)

#### Focus on Pinned tiles

* ❌ Pocket tile title + description
* ✅ Pinned tile title (only on currently focused tile)

![Homescreen - focus Pinned tile 1@2x](https://user-images.githubusercontent.com/51007/57596394-99f89b00-759e-11e9-8d1c-0f59b18a6bc7.png)

#### Focus on News & politics

* ❌ Pocket tile title + description
* ❌ Pinned tile title

![Homescreen - focus News   politics tile 1@2x](https://user-images.githubusercontent.com/51007/57596237-bb0cbc00-759d-11e9-94bf-f8cfaf2759cd.png)

## Custom pinned tiles

### For simplicity, decide which of these are important to fix:

> * Custom pinned tiles with screenshots
> * Custom pinned tiles with placeholder letter text

If screenshots fail to fetch, what about using favicon, `apple-touch-icon`, `og:image`, etc. before we resort to placeholder letter?

## Pinned tiles

### While bundled tiles and custom tiles are in the same channel, we always need to display titles

Agreed. Thanks for thinking of this scenario.

Yes. We should show a title on each pinned tile. But we should also only show title for item that has a focus ring around it. This means that only one item will be titled. This makes our titling behaviour consistent with Pocket tiles.

![Homescreen - focus Pinned tile 1@2x](https://user-images.githubusercontent.com/51007/57596939-53f10680-75a1-11e9-929a-0d373f8686e1.png)

What do you think?

### Update the appearance of bundled tile assets, or wait until they move into categories?

I’m happy to update the appearance of our bundled tile assets now, but the implementation may be too complicated that we might want to wait!

My tile construction formula:

(`logo svg` × `scaling-value`) sitting on top of (`tile-size` with `background-color`)

#### Tile sizes and scaling values

| Number of tiles per row | Tile size | Logo scaling value | Note |
| --- | --- | --- | --- |
| 5 | 150×84 | 1× | Reserved for future use |
| 4 | 193.5×108 | 1.29× | Pinned and category tiles use this size |
| 3 | 266×149 | 1.7733× | Pocket tiles use this size |
| 2 | 411×231 | 2.74× | Reserved for future use |

![logo-scaling-row@2x](https://user-images.githubusercontent.com/51007/57598196-599d1b00-75a6-11e9-86c8-aac53414d388.png)

#### Example

1. Logo <img width="110" src="https://user-images.githubusercontent.com/51007/57598270-aed92c80-75a6-11e9-91a2-0b1bfcd26297.png">
2. I want to use it as a tile inside a channel, so the logo SVG should be multiplied by `1.29×`
3. As a tile inside a channel, its tile size is `193.5×108` pixels
4. Its background colour is `#6d6e70`

#### Result

<img width="193.5" src="https://user-images.githubusercontent.com/51007/57598566-ccf35c80-75a7-11e9-9138-073fab93496b.png">

I wonder whether this formula can easily be adapted to our development and scale in the future, or if we need another approach?

**Comment by brampitoyo** [comment]
@mcomella Site tile logo SVG files: https://drive.google.com/drive/folders/12112POKFlky5JW9TIPejFr9EpMg5JepQ

**Comment by mcomella** [comment]
Bram and I discussed Bram's mocks above https://github.com/mozilla-mobile/firefox-tv/issues/2209#issuecomment-491685222. To simplify engineering requirements, we agreed upon an intermediate step, which is roughly similar to where we are now:
- Tile text (titles, Pocket descriptions) will stay on the screen at all times
- We will not fetch favicons
- The Pocket channel will be sized the same as other channels

Hiding and displaying the tile titles is important for the final sidebar design (where channel titles and tile titles are all hidden to allow quick scanning) so I created a list of **follow-up requirements** in the first comment to capture these important items we don't want to forget about. When they're actionable, we can consider filing bugs for them.

**Comment by mcomella** [comment]
I filed https://github.com/mozilla-mobile/firefox-tv/issues/2260 to check the performance of SVGs.

**Comment by mcomella** [comment]
@brampitoyo Please correct this if this is incorrect: I can't remember exactly. We should also:
- Keep focusing the last item in the channel behavior consistent between Pocket and other channels (i.e. right now, the last focused channel element stays on the right side of the screen so, for simplicity, we should leave it consistent).

**Comment by mcomella** [comment]
I think the UX requirements for the home screen for this iteration are gathered. 

@brampitoyo If you agree, can you add your mocks to the UX deliverable bug #2238 and, if they don't match our requirements (as I mention the changes in the few comments above), add in the changes to that list of requirements? Then close this issue. Thanks!

**Comment by brampitoyo** [comment]
@mcomella wrote:
> Keep focusing the last item in the channel behavior consistent between Pocket and other channels.

I’ve updated my mocks to suit. I will add it to #2238 then close this issue.
