### ISSUE TITLE
Visiting a pinned site shows "Pin to homescreen" in the tool bar hints

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#2236]
## Steps to reproduce
- Open FFTV
- Go to any Pinned Tile
- Open Overlay

### Expected behavior
- Pin icon in the tool bar should be in "pinned" state (hint shows "Unpin")

### Actual behavior
- Hint shows "Pin to homescreen" and appears to be in "unpinned" state

### Device information
* Fire TV device: ?
* Latest affected Firefox version: ?
* Earliest affected Firefox version: ?

### TODO
- Verify if we need a string or not
- Add a string if we do ASAP (partial translation okay?)
- Implement

**Comment by liuche** [comment]
I think there are a few options here:
- We don't have a Content-approved string, although we could likely just use "Unpin from homescreen" in that case (and optionally get some feedback from @mheubusch's team on this, but my guess is that since it follows the format of the "Pin to homescreen" this would be fine)
- This wouldn't be localized, but since it's on the main page, we could land this string now to get 2 weeks of localization, and then land the change in next sprint. What do you think, @athomasmoz ?

In any case, we should land the string so we can get it exported.
