### ISSUE TITLE
Verify focus behaviour after Pocket channel is merged

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/firefox-tv#2289]
Address after https://github.com/mozilla-mobile/firefox-tv/pull/2178 is merged

### Vision statement / What / Requirements
Android default focus behaviour is streaky and can be inconsistent. We need to make sure focus navigation works as intended for all the directions (up, down, left, right) specifically after multi-channels in in place.

### Impact
Confusing focus navigation would be a bad UX

### Acceptance criteria
Focus navigation between each channel is UX verified (@brampitoyo)

**Comment by liuche** [comment]
@psymoon I noticed that when you hit left from the Turbo mode button, it goes to the Pocket channel row (not the nav bar, or not moving at all, as expected)

**Comment by psymoon** [comment]
@liuche Ah, it looks like we never handle Turbo button focus (https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/main/java/org/mozilla/tv/firefox/focus/FocusRepo.kt#L129).

**Comment by mcomella** [comment]
@psymoon Is there anything else to do here or can we close this?

**Comment by brampitoyo** [comment]
@psymoon I will have the time to verify these behaviours this week. Do you have a link to an APK that I can install?

**Comment by psymoon** [comment]
@mcomella once bram verifies that it's good then we can close it

@brampitoyo build off master should be good

**Comment by brampitoyo** [comment]
I checked the APK today, and everything looks great!

The only issue I found was forgetting focus position when a row reaches its end. Unfortunately, this will take a while to explain, but I’ll illustrate it with pictures.

-----

### How tile focus should work all the time

Let’s take these two rows as an example: Pinned Sites and News. The first item on Pinned Sites is YouTube. The first item on News is CNN.

![homescreen](https://user-images.githubusercontent.com/51007/58609352-60909100-82fb-11e9-9209-94c8cfec260c.png)

If I press down from YouTube, what tile should get highlighted? CNN.

![homescreen](https://user-images.githubusercontent.com/51007/58609392-874ec780-82fb-11e9-871c-bb39d608c672.png)

I press right and go to Fox News.

![homescreen](https://user-images.githubusercontent.com/51007/58609443-af3e2b00-82fb-11e9-8899-645bc517cce7.png)

If I press up. what tile should get highlighted? YouTube.

![homescreen](https://user-images.githubusercontent.com/51007/58609504-dd236f80-82fb-11e9-8976-674789b74354.png)

So far so good. This is the behaviour that I would expect in all the tiles.

-----

### Tile focus at the end of each row doesn’t behave consistently

I now press right until I reach the third-to-last, third-to-last, or very last tiles in this row: Flickr, Instagram and Pinterest, respectively.

![homescreen](https://user-images.githubusercontent.com/51007/58609651-75b9ef80-82fc-11e9-8cd3-1bd3a8fff08f.png)

If I press down from Flickr, which tile will get highlighted? If we’re being consistent, we’d say Fox News. But instead, **the News row moves one tile to the right to highlight Washington Post**.

![homescreen](https://user-images.githubusercontent.com/51007/58609765-e95bfc80-82fc-11e9-8bc1-2f03d0af1850.png)

When I press up, somehow FFTV has forgotten that the last tile I selected was Flickr. It simply returned me back to Hollywood Reporter.

![homescreen](https://user-images.githubusercontent.com/51007/58609822-35a73c80-82fd-11e9-88b4-9dc922662afe.png)

I now press right again until I reach Instagram: the second-to-last item in this row.

![homescreen](https://user-images.githubusercontent.com/51007/58609869-64bdae00-82fd-11e9-861c-211ed7ea948a.png)

When I press down, which News tile will be highlighted? Again, logic says Washington Post, but instead, **the News row moves two tiles to the right to highlight Wall Street Journal**.

![homescreen](https://user-images.githubusercontent.com/51007/58609904-9171c580-82fd-11e9-8e0a-99ee71f45b22.png)

I now press right on News until I reach the last four tiles: CBS News, Huffington Post, Vice and CNN.

![homescreen](https://user-images.githubusercontent.com/51007/58610049-2d9bcc80-82fe-11e9-9717-bc31b227859d.png)

The behaviour I expected is: whatever tile I press up/down from, FFTV will remember the focused tile on that row.

Instead:

* If I press up from CBS News, I get Hollywood Reporter
* If I press up from Huffington Post, I get Flickr
* If I press up from Vice, I get Instagram
* etc.

**Comment by Baron-Severin** [comment]
@brampitoyo @athomasmoz should we block on this focus behavior, or is it fine if this is addressed in a follow up?  It's probably not a simple fix.

**Comment by athomasmoz** [comment]
The current behaviour really catches you off guard. I'm okay if we don't block on it, but I'd like to follow-up with it next sprint.

**Comment by mcomella** [comment]
**Disclaimer:** this only makes sense if I understand the code correctly and I may not.

> Ah, it looks like we never handle Turbo button focus

If I understand the code correctly, it really surprises me that we have to set next focus for every view in every direction. For example, how turbo mode [needs to dynamically change the focusLeft target.](https://searchfox.org/mozilla-mobile/rev/baea1da12f2d7dea29c0018bbf62a520c7b36091/firefox-tv/app/src/main/java/org/mozilla/tv/firefox/focus/FocusRepo.kt#254). I think this – trying to reimplement Android's focus behavior by hard-coding focus for our specific views – might be part of the reason we're seeing so many focus bugs.

I wonder if we can simplify this by setting next focus **on the parent containers** (e.g. the presumably LinearLayout containing the toolbar buttons) rather than the individual views within the containers. The parent container should be smart enough to handle focus changes within the container and, with our additions, can focus other parent containers. I think this should be possible because Android has a conception of focusing the parent after focusing descendants, even if that's not what I think the user would see: see [`ViewGroup.FOCUS_AFTER_DESCENDANTS`](https://developer.android.com/reference/android/view/ViewGroup#FOCUS_AFTER_DESCENDANTS), which I think is the default.

@psymoon Does this make sense. Do you think this is possible?

**Comment by athomasmoz** [comment]
Closing this story as the verification has been done. New bug opened to address the issue found #2384
