### ISSUE TITLE
Removing pinned tile breaks focus

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#2327]
## Steps to reproduce
- Long press pinned tile
- Select remove

### Expected behavior
- Focus moves to new tile

### Actual behavior
- Focus is lost
- Focus can be regained by pressing directions on the D-Pad, but will reappear in unexpected places

### Device information
* Fire TV device: 4K Stick
* Latest affected Firefox version: 0cf006be74be54307b8859c928d3899fb2d6f657
* Earliest affected Firefox version: introduced in #2280 (59003617bcbae9de836bd06e3278195a84cd898f is unaffected)

**Comment by psymoon** [comment]
This appears to be a regression from https://github.com/mozilla-mobile/firefox-tv/commit/c3d105f524aaab98e3aa27c170f16acf5df2e269. This definitely used to work before 🤔

**Comment by psymoon** [comment]
Okay, this is caused by https://github.com/mozilla-mobile/firefox-tv/commit/7f2b84672a94f262dfe6a0281382b0d93b5f391a, and switching `ListRowView` back to `RecyclerView` fixes this problem. If we want to use `leanback` API, we need to use `leanback.Presenter`, not `RecyclerView.Adapters` (because the wrappers have their own internal focus logic). 

@liuche Why do we need to use `ListRowView`?
