### ISSUE TITLE
Finalize Strings for Account Login & Send Tab

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2442]
### Why/User Benefit/User Problem

As a FFTV user, I want to learn about the send tab feature & get support setting it up, so that I can watch videos found on my phone/laptop through my TV

### Acceptance Criteria (how do I know when I’m done?)

* Strings have been finalized for account log in flow
* Strings have been finalized for send tab

### Not included

* Localization of strings

**Comment by liuche** [comment]
@brampitoyo would you have a more final date getting these?

**Comment by brampitoyo** [comment]
Pinging @mheubusch for update.

I will also have a thorough second look at the original strings I wrote, as soon as possible, next week.

**Comment by athomasmoz** [comment]
Spreadsheet of strings https://docs.google.com/spreadsheets/d/1z852T9AKhFpQFq8JcX633-zsC81vxAkKYKyilwdistU/edit#gid=0

Currently working on finalizing

**Comment by brampitoyo** [comment]
@athomasmoz I’ve checked with Michelle to finalise the strings in the spreadsheet. We should now be ready to go.

Re: Firefox Preview. There is a push to promote Firefox Preview in Oct, but Fennec won’t be retired or replaced. Fenix’s ‘Preview’ moniker won’t be dropped just yet.

Knowing this, there won’t be confusion about ‘Firefox for Android’ vs. ‘Firefox Preview’. We’ve updated the spreadsheet so that it says ‘You can send tab using Firefox Preview’, and omitted ‘Firefox for Android’.

With the name ‘Firefox Preview’ firmly in place in October, we’re no longer worried that users will be confused that their ‘Firefox for Android’ won’t be able to send tabs. Although only implied, we hope that they will download Firefox Preview in the process (if they use Android).

With that change, our strings are now finalised and ready for localisation.

**Comment by liuche** [comment]
One problem here is that in Oct, we think the name "Firefox Preview" name will be changed to something else (to replace "Preview" with something else, but not dropping it). So this might be problematic, or we might need to change the strings later? Maybe @mheubusch has more insight into the re-naming.

**Comment by athomasmoz** [comment]
FYI I've reached out to Vesta about this. She will confirm the naming

**Comment by liuche** [comment]
After checking in with Vesta the app will still be called Firefox Preview when this launches so we're fine with the existing.
#2643 for landing the strings, so we can close this.
