### ISSUE TITLE
Choose FxA device name

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2516]
### Vision statement / What / Requirements
On accounts.firefox.com and in other devices, a signed user will see an icon for the device (e.g. a TV) and the device name. Currently, we have this set as a placeholder: "Firefox for Fire TV". We should come up with a final name that's hopefully localizable.

### Acceptance Criteria

* When choosing a device to send a tab to, Firefox for Fire TV shows up with a name that will help users identify the device
- [x] Final device name is implemented in FxaAccountManager initializer
- [x] Final device name is localizable or does not need to be localized

### TASKS

* Determine if we can use Bram's [suggestion below](https://github.com/mozilla-mobile/firefox-tv/issues/2516#issuecomment-521049642)
* If not, then use our app name: Firefox for Fire TV or a limited set of more specific device names (ie. cube)

**Comment by brampitoyo** [comment]
@mcomella Amazon already provides a name for all its devices. It’s quite hidden. To access it, you either go to:

* On the device: Settings → System → About
* On the web: [Manage Your Content and Devices](https://www.amazon.com/hz/mycd/myx#/home/devices/1)

![Screenshot_2019-08-14 Amazon com Manage Your Content and Devices](https://user-images.githubusercontent.com/51007/62984715-5ad13300-be88-11e9-8a6d-e05f9a8f988f.png)

I agree with your suggestion of prefixing the device name with _“Firefox on…”_. To that, I’d like to complement it with the device name that comes from Amazon.

So, instead of:
> Firefox on Fire TV Stick
> Firefox on Echo Show

We have:
> Firefox on Bram’s Fire TV Stick
> Firefox on Bram’s Echo Show

What do you think?

**Comment by mcomella** [comment]
The name appears on device (Settings -> My Fire TV -> About -> Fire TV Stick) but I'm not sure if it's possible to access it via the Android APIs. It's actually pretty hard on Android to get identifying device information and we might have to convert it from device codes (e.g. AFTT -> Fire Stick 2nd Gen).

Whoever is implementing this bug should do the research to identify what's feasible.

**Comment by abodea** [comment]
Verified as fixed in v4.5-LAT3.
