### ISSUE TITLE
Identify root cause of testGeckoDebugUnitTest intermittent hang

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2539]
Follow-up to #2378.

### Vision statement / What / Requirements
We identified two tests as the failure point of our unit test task and `@Ignore`d them: https://github.com/mozilla-mobile/firefox-tv/pull/2517 We should look at the failures in these tests to identify if:
- There is a problem in the production code
- There is a problem in the test
- There is a problem elsewhere

### Impact
Given the tests are failing, we can have a bug in our production code that is causing problems we're otherwise not aware of.

When scheduling this bug, we should take into account the risks if there's a bug in the production code (i.e. look at the tests, see what the production bug could be, and use that to influence our decision).

### Acceptance criteria
- [ ] Tests are re-enabled and passing without intermittent failures
- [ ] Root cause of issues is found, or (timebox?) we have decided not to 

--- 

N.B: Daniela has noted upgrading gradle & robolectric appeared to fix the problem in 10/10 runs: https://github.com/mozilla-mobile/firefox-tv/pull/2431#issuecomment-510511604

**Comment by Baron-Severin** [comment]
@mcomella @dnarcese did either of you happen to save a link to any test runs that failed on these?

**Comment by dnarcese** [comment]
@Baron-Severin Here is one run with `--info` https://tools.taskcluster.net/groups/IEe3UIreTfKrP5jEUcAuyA/tasks/IEe3UIreTfKrP5jEUcAuyA/runs/0/logs/public%2Flogs%2Flive.log

**Comment by Baron-Severin** [comment]
TODO write comment about investigation (edit this comment), rewrite test to avoid problem, close story

**Comment by Baron-Severin** [comment]
## Fix TL;DR
If the code under test changes threads, use `RxPlugins` & `RxAndroidPlugins` to make sure it works properly during testing.  See "How can we avoid this in the future?" for details.

## What went wrong:
```kotlin
// PocketVideoRepo
open val feedState = _feedState.hide()
    .observeOn(AndroidSchedulers.mainThread())
    .distinctUntilChanged() // avoid churn because we may retrieve similar results in onStart.

```
The `observeOn` jumps on to the Android main thread.  Normally this would crash in a test and then be fixed, but Robolectric is allowing it to run.  For some reason, probably buried deep inside Robolectric, it’s working differently on CI than it is locally.  I was not able to work out why.

The fix is to tell the test to run this code on its default thread by including this in the test class.
```kotlin
// PocketVideoRepoTest
companion object {
    @JvmStatic
    @BeforeClass
    fun beforeClass() {
        RxAndroidPlugins.setInitMainThreadSchedulerHandler { Schedulers.trampoline() }
        RxAndroidPlugins.setMainThreadSchedulerHandler { Schedulers.trampoline() }
    }
}

```

_Normally_ only the first of those two calls should be necessary [(see this article for an explanation of the difference)](https://medium.com/@peter.tackage/overriding-rxandroid-schedulers-in-rxjava-2-5561b3d14212), but for whatever reason that is not working here.  Presumably some strange interaction with Robolectric.

## How can we avoid this in the future?

If your code under test changes threads, make sure that they’re being properly handled in the test file, either with a `TestScheduler` (to mock the passage of time) or `trampoline` (to force everything on to the same thread).  `setInit*SchedulerHandler` _should_ always be enough, but apparently not.  Some people always set both versions just in case, **and I think we should probably default to doing that** for the sake of simplicity.

## What's still unresolved?

- What is the difference is between local and CI environments?
- Why is `setInitMainThreadSchedulerHandler` insufficient here?

**Comment by mcomella** [comment]
Thanks for the write-up! It was clear and helpful - I really appreciate the "What's still unresolved?" step.

@Baron-Severin Should we create a JUnit Rule to make remembering this incantation easier and ensuring we call both consistently? e.g.:
```kotlin
@JvmField @Rule 
val rxMultiThreadRule = RxMultiThreadRule()
```

> What is the difference is between local and CI environments?

Initial thoughts:
- Linux
- Slower execution environment

**Comment by Baron-Severin** [comment]
Good idea.  I opened https://github.com/mozilla-mobile/firefox-tv/pull/2627.
I haven't seen this done before, so I also pinged a few friends for their
thoughts on whether this could lead to any weird problems.  Seems perfectly
fine to me.
