### ISSUE TITLE
Make Firefox for Fire TV User Agent distinct

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#257]

**Comment by cvan** [comment]
Apologies in advance for the drive-by comment. Feel free to ignore. I saw this issue linked to in my email, and I figured it might be worth sharing.

FWIW, Safari is no longer updating `User-Agent` strings (`navigator.userAgent`) in its latest Technology Preview build ([STP 46](https://webkit.org/blog/8042/release-notes-for-safari-technology-preview-46/)) and beyond:

> ### Privacy
> - Froze the user-agent string to reduce web compatibility risk and to prevent its use for fingerprinting

Also, see [this relevant Tweet](https://twitter.com/rmondello/status/943545865204989953).

The whole "Do we keep stop changing the UA to discourage UA sniffing?" discussion is probably one worth on having on the [Mozilla `dev.platform` mailing list](https://groups.google.com/forum/#!forum/mozilla.dev.platform), but I figured I ought to bring it up here.

**Comment by miketaylr** [comment]
As is, it's impossible to know if a user is on Firefox TV, or just an older version of Focus an Android. That's either or good (can't get blocked by YouTube), or bad (won't get sent TV optimized content because there's no `TV` token in the UA string, certain "mobile" content assumes touch events, etc.)

We did a lot of research for the Firefox OS UA string (starting here...): https://bugzilla.mozilla.org/show_bug.cgi?id=1199592#c18, in case it's helpful.

**Comment by avesus** [comment]
> "certain "mobile" content assumes touch events"

is the most frustrating.

**Comment by athomasmoz** [comment]
Closing issue. This is not something we can tackle for now, due to issues mentioned in Mike's comment

**Comment by cvan** [comment]
Is there not a @media query for the `media` type? If not, ought we to propose one to the appropriate CSS spec?
