### ISSUE TITLE
Telemetry Not Logging

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#258]
STR:

1. Change TELEMETRY_APP_NAME_FOCUS_TV to "Sush TV"
2. Repeat steps 3 through 5 n times
3. Install Firefox, Launch Youtube, Play Video for a few minutes
4. Background Firefox
5. Foreground Firefox and continue to play video
6. Check dashboards - we don't see n events. 
https://sql.telemetry.mozilla.org/queries/50013#134406 
https://sql.telemetry.mozilla.org/queries/50012#134404

**Comment by Sdaswani** [comment]
@bkmunar please first try to reproduce my STRs and then make our telemetry fire in the foreground and see if that gets the event logged on the dashboard.

**Comment by mcomella** [comment]
I think there is debugging info in the console when we do telemetry uploads (or you can add it locally).

If the problem is the app is unable to upload while backgrounded, we could consider uploading when the app is started instead.

**Comment by Sdaswani** [comment]
Yes @mcomella firing in the foreground / launches is an easy fix so today @bkmunar should be able to tell us if that works.

**Comment by bkmunar** [comment]
Based on some research from me & @boek, it turns out pings were being malformed and sending back error codes when we backgrounded/foregrounded the app on the Fire TV (the old version). Jeff took out the space of the app name "Sush TV" -> "SushTV" and after that we were getting consistent logging for telemetry. 

It seems as if the old version of Fire TV wasn't properly sanitizing the requests that go to the server. However, being that there are still DAUs on the "Focus TV" telemetry chart, it seems like that's not a complete solution.

Maybe we can validate if the new version of the Fire TV is sending pings with and without the space in the app name? If we get consistent successful logging from both versions onto "SushTV" I feel like then that might be the solution to this--that the old version just doesn't like spaces in the app name

**Comment by Sdaswani** [comment]
Hoping this fixes the issue: https://github.com/mozilla-mobile/firefox-tv/pull/283

**Comment by Sdaswani** [comment]
Frank recommends we use this to confirm Telemetry: https://github.com/mozilla/gzipServer

**Comment by Sdaswani** [comment]
I think we can close this issue after the fix in 283. Telemetry looks good.
