### ISSUE TITLE
Moving the cursor and selecting things using the remote is clunky

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/firefox-tv#266]
Via Review:

The blue dot is a disaster. - The meeting of buttons is a matter of luck. The resolution of the control is not adapted to the HDMI resolution of the screen. The point is too big. If the buttons are unfavorable you can click 4 buttons at the same time. Have Firefox on my laptop. This app has nothing to do with the Windows browser (except the name). .... disappointing

https://www.amazon.de/review/ROKQLKUOFG780/ref=cm_cr_dp_title?ie=UTF8&ASIN=B078B5YMPD

**Comment by st3fan** [comment]
The dot moves too quickly for me. I think the movement is related to how long you press the down button on the remote, but I am having a hard time to press short enough to move a small amount to a link. This works better in Silk - maybe we can play with the speed a bit to match that?

**Comment by rtanglao** [comment]
the remote is smoother than using the firetv app on my iphone 7 plus but yeah it's not as smooth on either the real remote or the firetv app on iOS

**Comment by nils-ohlmeier** [comment]
I would say the difference is that with the "real" remote (aka the remote which came with my Fire TV stick) the blue dot only moves a fixed amount of pixels over the screen for a single click. I have not tried what happens when keep the ring on that remote pressed down.
But on the iPhone remote app just slightly touching the cursor area appears to result in lots of "click" events. So the blue dot moves 10 times as far as with the "real" remote.
