### ISSUE TITLE
Back button does not work in YouTube

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/firefox-tv#270]
STR:

* Cold start Firefox
* Open the YouTube shortcut
* Hit the back button

Expected: going back to the home screen
Actual: nothing happens

This may also be my inexperience with Fire TV and this new product, but I can't figure out how to get back to the main screen to enter a different website address. Had to restart my Fire TV to get out of YouTube.

**Comment by st3fan** [comment]
Oh you can get back to the home screen via the hamburger menu. That works well. But I sort of expect the back button to do this too. Not sure if that is fair. Habit from other browsers?

**Comment by bbinto** [comment]
via Review

"How to exit youtube..... I see lots of people saying they can't exit youtube in firefox. When in youtube, hit the menu button on the remote (it's the one to the right of the home button). That will open up a side bar on the left of your screen and then you can click down until you hit "home" and that takes you back to the main firefox screen that shows the bookmarks and allows you to search the web. "

**Comment by liuche** [comment]
We remapped "back" to esc in order to leave fullscreen Youtube videos, but we should figure out a workaround to also do back.

**Comment by liuche** [comment]
There are a few options that we discussed, but we're going to table this for now because it's too hacky. Moving out of 1.1.

Hacky options:
- Use "long-press" back to navigate Youtube back actions (or going back to Home)
- Take periodic screenshots and try to guess when back should be "Youtube esc" or "navigation back"

Better but awkward options:
- Show hint explaining how to go to homescreen from Menu

**Comment by Sdaswani** [comment]
Moving this out of 1.1.

**Comment by liuche** [comment]
Should be fixed in the near future.
