### ISSUE TITLE
Define FxA Profile screen error state

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#2721]
### Why/User Benefit/User Problem
It is possible for FxA authentication to succeed, but without a valid profile being sent to us.  Currently, that error state looks like this (not terrible, but also could be improved):

![fxa-no-profile](https://user-images.githubusercontent.com/13170306/63468857-b1f17d80-c41d-11e9-8f45-7d7476dfc64f.png)

Note that if a profile is later successfully pulled down, this screen will automatically update to use it.

### Acceptance Criteria (how do I know when I’m done?)
@brampitoyo & @athomasmoz should decide what this error state should look like, so that engineering can build it out.

**Comment by brampitoyo** [comment]
The easiest way to resolve this issue is by rewriting:

> Signed in as

to

> Signed in

With no other change in the design (ie. keep using the generic avatar icon, buttons, etc.)

Here, our message is less “warning: an error occured” and more “we’re just waiting for a piece of information”.

Hopefully our users won’t have to wait for a long time until their profile info is successfully received.

**Comment by dnarcese** [comment]
Blocked on merging until after the current release (4.5), so that the string has time to be localized.
