### ISSUE TITLE
URL autocomplete seems to break text entry from Fire TV remote app on Android

### ISSUE THREAD

**Issue by lmorchard** [mozilla-mobile/firefox-tv#276]
Rather than use the physical remote, I tried using the Fire TV remote app on my Android phone to enter a URL using my phone's keyboard. It seemed like every character I tried entering got interrupted by the autocomplete feature, and the text on my phone and on the TV screen got out of sync.

**Comment by AaronMT** [comment]
This is preventing me from using my phone to type a URL quickly.

**Comment by mcomella** [comment]
The behavior of our InputConnectionWrapper (in InlineAutocompleteEditText) is different between the remote and soft keyboard:
- Entering a key on the soft keyboard fires, `commitText` with the selected letter
- Entering a key on the remote fires, 'comimtText` with the empty string, `deleteSurroundingText`, and fires `commitText` with the selected letter

**Comment by mcomella** [comment]
I created a clean app to test if we could sub in the `AutocompleteTextView` or `MultiAutocompleteTextView` for our custom EditText, thinking the default IME could be smart about these views, but it appears that is not the case: the views will add their autocomplete suggestions in the UI underneath the soft keyboard but there is no way to access them with the soft keyboard.

It seems we got lucky that our inline autocompletion just worked!

**Comment by mcomella** [comment]
The app remote doesn't appear to show up as an active IME so I don't think we can confidently handle the input differently: I checked `﻿Settings.Secure.getString(..., Settings.Secure.ENABLED_INPUT_METHODS)` and for `DEFAULT_INPUT_METHOD` and only the default IME appears in the result.

---

This is how the Focus autocomplete currently works:
- `onCommitText(<letter-typed>, /* newCursorPosition */ 1)` is called, which is expected to append the character to the current cursor position and move the cursor forward one character
- `BaseInputConnection.replaceText` (called from ^), which does the appending ^. If autocomplete is available, it inlines it so "ap|ple.com", where | is the cursor and we type "c", turns into "apcple.com" in the Editable (temporarily)
- `InlineAutocompleteEditText.TextChangeListener.afterTextChanged` is called, which calls `removeAutocomplete` to remove the current autocomplete (or `onAutocomplete` if the autocomplete stays the same). It appears to do this with a span, `InlineAutocompleteEditText.AUTOCOMPLETE_SPAN`, rather than selecting the text or similar
- `InlineAutocompleteEditText.mFilterListener.onFilter` will be called, which calls `UrlInputFragment.onFilter` -> `UrlAutoCompleteFilter.onFilter` -> `InlineAutocompleteEditText.onAutocomplete`, which appends the new autocomplete text, if it's available.
- Once again, `InlineAutocompleteEditText.TextChangeListener.afterTextChanged` will be called with the final text

I'll investigate if the behavior is the same with the hardware remote on the Fire TV.

**Comment by mcomella** [comment]
The hardware remote on Fire TV appears to behave similarly to Focus.

Some differences on the app:
- The cursor is at the end of the autocompleted text, rather than before it
- Before the soft keyboard is up, if the input contains text and you select the input to raise the soft keyboard, the app *will display the empty string* while the text in the soft keyboard matches the text in the input. Typing a letter on the app will replace the soft keyboard text with the typed letter.

And as far as call order is concerned, when you have "a|mazon.com" and type "p":
- `commitText("", 0)` is called - I assume this should be a no-op, but maybe it calls below.
- `deleteSurroundingText(<max_value>, <max_value>)` is called. This should clear the whole input but we override it so...
- `removeAutocomplete` gets called, which calls `text.delete(start, text.length())`, which deletes all the text including the new character
- `afterTextChange` gets called and the text is only the existing text, "a" without autocomplete.

Since you want the text to complete, you now type "p" again:
- `commitText("", 0)`
- `deleteSurroundingText` is called. It calls removeAutocomplete but since there is none, the super impl is used
- `afterTextChanged` is called. The text has been deleted so it's the empty string
- `commitText("ap", 1)` is called. This should replace the now empty text field with "ap" and advance the cursor to the end of the text
- `afterTextChanged` (2nd) is called with text "ap". This calls `onAutocomplete`, which calls...
- `afterTextChanged` (3rd) is called with text "apple.com". The cursor on the remote app is moved to the end of the input

It looks like the remote works by deleting the existing text and setting the input text + new, rather than just appending a character like the soft keyboards.

---

The `InlineAutocompleteEditText` is pretty complicated so I think I can only come up with a patch fix (rather than identify if we're actually doing things in an incorrect way – it's strange how often `afterTextChange` gets called for example). Places to investigate:
- When we delete the autocomplete span, we delete to the end of the text – maybe we can delete to the end of the span instead?
- Maybe it help if we could position the cursor in the remote app in the correct location? Maybe that doesn't matter if we delete the correct span though. It could mess up if the user manually repositions the cursor though.

**Comment by mcomella** [comment]
**I decided that I'm going to try to disable autocomplete when the remote is in use, rather than trying to put autocomplete on the app**:
- I don't have a solid understanding of how the IME interacts with the Editor (our InlineAutocompleteEditText), which I think is important to creating a proper solution
- It may not even be possible to add autocomplete to the app (the way we're doing it): the remote seems to take several async operations to update: 1) type nothing, 2) delete all text, 3) type the original text + the new character. In the mean time, it keeps its own record of what the on-screen text should be. If we update the text on the device, the remote may never be able to synchronize properly
- There are many edge cases to worry about: entering text with(out) autocomplete, deleting text (and updating autocomplete), moving the cursor manually, text selection, etc.

My current proposal for fixing (to be tested):
- If we receive `commitText("", ...`, it's the app. Disable autocomplete entirely (even for the remote) until the soft keyboard is dropped and reopened - it's unlikely the user will switch from the app to the remote
- We may be able to determine the soft keyboard open/close through a focus change listener.

**Comment by Sdaswani** [comment]
Sounds like a good plan @mcomella - thanks for looking into this.

**Comment by mcomella** [comment]
> If we receive commitText("", ..., it's the app.

Unfortunately, not true: pressing "clear" on the soft keyboard has the following effect:
- `commitText("", 0)`
- `deleteSurroundingText(<everything>)`

This is the same steps that are taken when a single character is added by the remote – apparently the remote runs a clear command and then sets the text field to the entire text.

Maybe we can:
- Ensure we don't do anything that messes up the remote for a clear command
- Either:
    - Disable autocomplete after one character for all devices (we can't tell the difference between the remote and app at this point)
    - Do nothing (assuming the first autocomplete does not mess up remote users). Users on the remote will see autocomplete for the first character they type but it will be disabled forever after that
- If multiple characters are entered at once (a likely indicator of the remote app), disable autocomplete

We can also consider re-enabling autocomplete if only one character is receiving (but that depends on the decisions above).

**Comment by mcomella** [comment]
Turns out we can identify key presses from different devices with `KeyEvent.getDeviceId()` and [may be able to identify which device is the remote](https://developer.amazon.com/docs/fire-tv/identify-controllers.html#identifying-controller-features). However, it doesn't appear that there's a KeyEvent fired for input from the remote so while we have a reference to the remote when it makes input, we don't have a reference to the remote app. Options:
- (comment above) Check the device from the `commitText` arguments - this is delayed and may require us to change the autocomplete patterns though.
- Whitelist input devices for autocomplete (since we can determine which presses come from the remote. This seems error-prone.

**Comment by mcomella** [comment]
QA notes: please verify that autocomplete is disabled for the Fire TV Remote app (iOS and Android) and enabled for the hardware remote. Please also verify that attempting to use both (remote app + hardware remote) is acceptable.

**Comment by npark-mozilla** [comment]
To me it looks good, only unusual thing is that I can type on the homescreen url bar without selecting the url bar, by pressing the keyboard icon on the top right corner of the fire app. Even though it accepts keyboard input, it doesn't go to the URL when enter key is pressed - one has to select the URL bar to make screen keyboard visible, then press enter.  This also happens on overlay, which can make the text on Fire app and screen out of sync. for example:

- Open URL, and when the site is loaded, open overlay
- Highlight settings or any other button other than the URL bar
- Press keyboard icon on the Fire app, and type 'abc'
- With the remote, select the URL bar, and type 'def' on the Fire app keyboard
Expected:
Both the Fire app and URL bar on screen should show same text
Actual:
Fire app keyboard shows 'abcdef', while the URL bar only displays 'def'.
Minor issue, I'll copy above as a separate bug, but might worth keeping track of it.
