### ISSUE TITLE
If tab is received while Firefox is in background, show received tab when Firefox is opened

### ISSUE THREAD

**Issue by athomasmoz** [mozilla-mobile/firefox-tv#2807]
### User Problem

If a user sends a tab when Firefox is in the background, it is never received. This could cause confusion & require the user to go back and send the tab again.

### Acceptance Criteria (how do I know when I’m done?)

* Firefox still receives tabs when in the background
* User sees their latest received tab the next time Firefox is opened (the currently open tab is added to backstack, as they would be if Firefox was open)
* User sees toast with the tab to clarify where it came from

### Not included

* This story doesn't include notifying the user about a received tab when they're not in the app. That's #2654

**Comment by Baron-Severin** [comment]
@athomasmoz @brampitoyo I misread the A-Cs during implementation.  In my PR, if a tab is sent while FFTV is backgrounded, the app will open itself and then navigate to the tab.  Was that intended to be a follow up, or is it undesirable behavior?  I can remove it if need be.

**Comment by brampitoyo** [comment]
@Baron-Severin 

> …if a tab is sent while FFTV is backgrounded, the app will open itself and then navigate to the tab. Was that intended to be a follow up, or is it undesirable behaviour?

Yes. This is an intended behaviour.

When the sent tab takes over, it should still be possible to go back in history to the page that was previously opened (assuming there’s already a page open when FFTV is in the background).

**Comment by Baron-Severin** [comment]
> When the sent tab takes over, it should still be possible to go back in history to the page that was previously opened (assuming there’s already a page open when FFTV is in the background).

@brampitoyo Yep, that works as expected here.  Thanks!

**Comment by brampitoyo** [comment]
@mcomella Earlier today, I talked with @Baron-Severin to clarify the behaviour.

Originally, I thought that Firefox sits in the background only when the user presses the Home key and their current location is the Fire OS homescreen. In this case, we want tab received to automatically open Firefox.

But you mentioned the fact that it’s possible for Firefox to sit in the background while another app is currently open. In that case, we definitely don’t want to interrupt the user’s activities.

I asked @Baron-Severin whether it would be possible to have different behaviours for different conditions:

* IF user location is homescreen, THEN auto-open Firefox when tab is received
* IF user location is another app, THEN store tab in queue when tab is received. User must manually open Firefox to get sent tab.

If that’s not possible, then I agree with your assessment. Our default behaviour should be never to auto-open Firefox when tab is received, because of a high chance of user interruption.

-----

Severin and I also the fact that we still want to show a system-level notification when a tab is received. We knew that it’s not very easy to see. It sits on the bottom right hand corner of the screen for only a few seconds. Nevertheless, it’s still important in case the user wants to open the tab straight away without going back to the homescreen and manually finding/selecting the Firefox icon.

We will file a separate issue for this.

**Comment by abodea** [comment]
Verified as fixed on the v4.5-LAT3 build.
Note that I send at least 10-15 tabs while the FFTV was in background and when I opened the app, the sent tab was always opened.
