### ISSUE TITLE
Loading/Progress indicators

### ISSUE THREAD

**Issue by phlsa** [mozilla-mobile/firefox-tv#287]
We need some kind of progress indicators to give the user feedback that their input has been processed. Some sites (like YouTube) handle this themselves, but most »normal« websites don't. After clicking a link or entering an address, nothing happens for a while or the screen just turns blank without any indication as to whether the browser is still working.

**Comment by liuche** [comment]
This should be added to the bottom of fragment_browser.xml.

**Comment by bkmunar** [comment]
@lime124 please fix 
<img width="1223" alt="screen shot 2018-02-08 at 12 01 42 pm" src="https://user-images.githubusercontent.com/8356717/35995362-ec7ba07a-0cc7-11e8-94b5-50e681bc3911.png">

**Comment by lime124** [comment]
we're working together via slack to get something implemented. it's going to be more of an animation than a bar because of the overscan issue. we're working with a couple ux folks to bring the desktop tab loading indicator to tv

![browser](https://user-images.githubusercontent.com/287322/36003128-86ecc22e-0ce1-11e8-82e9-1a61ce48258d.png)

**Comment by bkmunar** [comment]
Closed with https://github.com/mozilla-mobile/firefox-tv/pull/496
