### ISSUE TITLE
[FxA] The Onboarding images after login are not translated on other languages then English

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2883]
## Steps to reproduce
1. Change the language on any other expect English.
2. Launch FFTV.
3. Login with valid credentials.
4. Observe the Onboarding images.
### Expected behavior
The onboarding images are displayed in the selected language.
### Actual behavior
The onboarding images are displayed in English no matter what language is selected.
### Device information
* Fire TV device: **`Fire TV Stick 4k`**
* Latest affected Firefox version: **`4.5-LAT4`**
* Earliest affected Firefox version: **`4.5-LAT3`**
* Turbo Mode: **`On and Off`**
![20190920_175035](https://user-images.githubusercontent.com/42831109/65341670-8c50c300-dbd9-11e9-85d8-c95845eb9d3b.jpg)

**Comment by mcomella** [comment]
The obvious solution is provide a separate image asset per locale but I’m concerned how much space one of these large banner images for each locale will take up. It’s currently 103k for english so it’d be ~800k for an image that users see once.

**Comment by brampitoyo** [comment]
@mcomella @athomasmoz Let’s try replacing this image with a ‘universal’ illustration solely composed of shapes and icons – no word.

1. The illustration:
    * Allows users to identify what device they have, based on the position of the URL bar
    * Shows users where to click/tap to access the send-share menu
2. The instruction text tells users what each button and menu item say

What do you think?

![Homescreen - Receive tabs onboarding 2@2x](https://user-images.githubusercontent.com/51007/65397585-6e67a600-de05-11e9-9ccd-c87c845b7101.png)

Source image: https://drive.google.com/file/d/1LKwhp6_n71C0PuXiyTxYyYQGUtZDkVXM/view?usp=sharing

![receive_tabs_onboarding_2](https://user-images.githubusercontent.com/51007/65397543-0749f180-de05-11e9-9701-5302e00af00c.png)

**Comment by mcomella** [comment]
@brampitoyo Interesting! I didn't consider what this would look like without text. However, I'm concerned it's lacking a little context.

As someone who has used send tab on desktop, that illustration made sense to me. However, having not used send tab on Fenix or iOS, I was confused by those and had trouble distinguishing the devices or that they were even mobile devices.

I wonder if we could try:
- Add in Android and iOS icons to disambiguate
- After the initial release, overlay the image with localized text, e.g. "Android", "iOS", "desktop" or even "Firefox Preview", "Firefox for iOS", etc.

Also, I'm not sure what the circled screen on the right is supposed to indicate.

Disclaimer: I haven't tried this on a TV – it may look different there – and I saw the isolated image before I saw it in the onboarding screen with the text so that may have affected my opinion.

**Comment by brampitoyo** [comment]
@mcomella That was my concern, as well. Unfortunately, because the image contains no text, we rely on the caption to do the bulk of the explanatory work. We hope it’s good enough to do that.

Let’s try adding platform icons:

![Homescreen - Receive tabs onboarding 2@2x](https://user-images.githubusercontent.com/51007/65464947-387efc00-deaf-11e9-9913-5fc735d025ec.png)

Or platform text:

![Homescreen - Receive tabs onboarding 2@2x](https://user-images.githubusercontent.com/51007/65465208-c955d780-deaf-11e9-87c0-866d762801b8.png)

While the illustration now risks being cluttered, having the text seems like the least-bad, best-compromise option. What do you think?

> I'm not sure what the circled screen on the right is supposed to indicate.

It’s supposed to indicate the final item that you’re supposed to select and what it looks like. I assume our device will show up with a TV icon?

**Comment by mcomella** [comment]
(having not viewed it on TV) I actually love the Android + iOS icons and while I can see what you mean, it doesn't feel too cluttered to me (then again, if users are in a rush...). Perhaps it'd feel less cluttered if we included a desktop icon (i.e. I think we usually use a laptop) and shrunk the desktop example too so that there are fewer horizontal lines?

> It’s supposed to indicate the final item that you’re supposed to select and what it looks like.

This isn't clear to me, nor am I sure how to improve it. Maybe we can shove an arrow in somewhere? Or maybe we can include our localized string for "Firefox for Fire TV" next to it.

> I assume our device will show up with a TV icon?

Yes, I believe it should but it's up to each application to implement that behavior and I'm not sure they've all done it yet: the TV icon is relatively new.

**Comment by mcomella** [comment]
QA: please verify the images in onboarding are localized in locales other than English (i.e. they have no text now so I think they should be localized :))

**Comment by abodea** [comment]
Verified as fixed using the latest build made from master. 
Everything looks fine.
