### ISSUE TITLE
Load default tiles from config

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#440]
Instead of hard-coding the tiles, they should be loaded from a config. This may eventually need to support locale-specific default tiles.

**Comment by Sdaswani** [comment]
Suggested Implementation?

1. Store Custom Tiles in a JSON in a flat file.
2. At startup, load the custom files from that flat file.

I think @bkmunar can work on this.

Let's not worry about localization right now - haven't heard from @bbinto that is in scope for 2.0.

**Comment by mcomella** [comment]
Our home tiles currently map a few values:
- String resource (i.e. title)
- Icon resource
- URL
- Position

The first two can have compile time checks (e.g. R.string.title, R.drawable.icon) and it'd be great if we could somehow keep these checked at compile-time, rather than shoving them into JSON. I haven't thought hard enough to come up with an ideal solution yet, but something to think about @bkmunar!

**Comment by bbinto** [comment]
@Sdaswani -- let's keep it simple and make a follow-up issue for past 2.0 re: localization

**Comment by Sdaswani** [comment]
@bkmunar your solution should anticipate localized tiles, but no need to implement it for 2.0.
