### ISSUE TITLE
Create overlay with navigation

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#444]
Make the navigation overlay screen.

**Comment by liuche** [comment]
@lime124 a few questions for you:
- Currently I just have Turbo mode look "disabled" but you can still select it, when it's off. Is that right? (see screenshot) I'm not sure what the "off" state should look like, could I get some more detailed mocks on the "off" state?
- When you click the "back" button on the overlay and the browser can't go "back" anymore, this should dismiss the overlay - correct?

![turbo-disabled](https://user-images.githubusercontent.com/1082253/35894448-8ef6fafa-0b67-11e8-958a-a38d0dfd66f6.png)

**Comment by lime124** [comment]
The key is going to be putting the icons in circles so that we can more easily show the various states.

Colors still TBD but this is the idea...

<img width="454" alt="screen shot 2018-02-06 at 2 11 56 pm" src="https://user-images.githubusercontent.com/287322/35926838-060d9a2e-0bde-11e8-9bfc-bc5996c8b17b.png">

**Comment by liuche** [comment]
@npark-mozilla btw, this removes the browselane so you can't go directly to settings from the home screen - #446 is filed for that.
