### ISSUE TITLE
Last home tile focused when hitting back from home screen url bar

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#495]
STR
1) Click url bar on home
2) type text
3) hit back

Expected: url bar focused
actual: Pinterest (last tile) focused

This is a follow-up to #493, where I came up with a quick solution that created this polish issue.

**Comment by boek** [comment]
So I think whats happening here is when the soft keyboard closes via the `Previous (Back)` button its triggering the event to focus on the next focusable element.

I tried to re-focus the urlInputBar on previous/backbutton pressed but that didn't work. Maybe it's happening earlier in the lifecycle?

I also tried messing with the focus order, but that caused problems with the remote navigation.

The last thing I attempted was seeing if any activity lifecycle methods were being called. But it didn't look like `onPause` or `onResume` ever got called with the soft keyboard.

**Comment by Sdaswani** [comment]
Thanks @boek I don't think is a release blocker, but we can discuss later today.

**Comment by liuche** [comment]
I'll take a look at this.

**Comment by liuche** [comment]
It's weird but I reverted #493 and there were no negative effects.

My guess is that what's happening is Amazon is popping up a custom Activity or view, and requesting focus on whatever view comes up there - when it closes, it doesn't know what view should be focused so one just randomly gets picked.

**Comment by liuche** [comment]
This is interesting and I'm wondering if the amazon keyboard is doing something funny - when you hit back while on the keyboard, the "Previous" button on the soft keyboard is highlighted and that's how it exits the screen, leading to problematic focus.

If you simply hit "Next" with an empty string, then the expected behavior occurs. My guess is that the keyboard is intercepting the "back" keypress, requesting focus on the button, and then the Android system has to figure out where to send the next focus.

**Comment by liuche** [comment]
Okay, basically the Amazon keyboard is garbage and calls `requestFocus` when asked to handle its own closing, which messes up the focus of other things - I tested this by replacing our urlbar with an EditText, so we could eliminate any funky stuff that the AutocompleteUrl is doing. This showed that any time you exited the keyboard (either by back or submitting an empty url), a home tile got focused.

The fix is to not let the Amazon keyboard handle its own closing.
