### ISSUE TITLE
New Instance of Webview Created Every Time?

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#507]
This report came from Amazon:

[02/20/18 01:27 PM] Haldeman, Andy: Hi Susheel, this is a minor issue, but our team noticed that if you try to start Firefox via ADB, it eventually hangs.
[02/20/18 01:28 PM] Haldeman, Andy: Here is the command:
[02/20/18 01:28 PM] Haldeman, Andy: adb shell am start -a android.intent.action.VIEW -n 'org.mozilla.tv.firefox/org.mozilla.focus.activity.MainActivity' -d 'http://youtube.com/tv'
[02/20/18 01:28 PM] Haldeman, Andy: We discovered it is because a new instance of Web View is created each time.
[02/20/18 01:28 PM] Haldeman, Andy: Not a high priority fix, but wanted to pass it along to your engineers.

**Comment by mcomella** [comment]
I think the ADB command may be creating new MainActivity instances, for which we do create new WebViews, but in practice, I don't think we create new MainActivities when a normal user is using it.

**Comment by Sdaswani** [comment]
@mcomella apparently using a voice command when we are in firefox causing another webview to be launched, according to Amazon.

**Comment by mcomella** [comment]
When starting via ADB, I can confirm this behavior: there are multiple references to WebView and multiple references to BrowserFragment. I'm guessing our BrowserFragments aren't getting cleaned up when we launch the activity again (maybe because we're adding them to the back stack?) and each one of them spawns a new WebView.

**Comment by mcomella** [comment]
When we get the new intent, we create an additional sessions, each of which has its own BrowserFragment and WebView: `MainActivity.onNewIntent` is being called when it's called from the command line, which calls `SessionManager.createSessionFromIntent` and creates the new session.

Since we only support one session, we probably just want to update the current page with the passed in arguments. This will have to take into account whether or not we have a session right now.

**Comment by mcomella** [comment]
I actually discovered our existing code is relatedly incorrect without launching a new activity:
```kotlin
        val browserFragment = fragmentManager.findFragmentByTag(BrowserFragment.FRAGMENT_TAG)
        val isSearch = !TextUtils.isEmpty(searchTerms)
        if (browserFragment != null && browserFragment.isVisible) {
            // Reuse existing visible fragment - in this case we know the user is already browsing.
            // The fragment might exist if we "erased" a browsing session, hence we need to check
            // for visibility in addition to existence.
            (browserFragment as BrowserFragment).loadUrl(updatedUrlStr)

            // And this fragment can be removed again.
            fragmentManager.beginTransaction()
                    .replace(R.id.container, browserFragment)
                    .addToBackStack(null)
                    .commit()
        } else {
            if (isSearch) {
                SessionManager.getInstance().createSearchSession(Source.USER_ENTERED, updatedUrlStr, searchTerms)
            } else {
                SessionManager.getInstance().createSession(Source.USER_ENTERED, updatedUrlStr)
            }
}
```

This code says we'll create a new BrowserFragment and a new session *every time* and URL is entered from the home screen. I confirmed this behavior by checking that there are multiple instances of BrowserFragment in the heap. Maybe this is what caused all the slow-down in the past.

**Comment by Sdaswani** [comment]
@mcomella is that only when a URL is entered, or also when a tile is chosen?

**Comment by mcomella** [comment]
I came up with a fix where we have at max one session:
```kotlin
        if (!sessionManager.hasSession()) {
            // Through the session observable, this calls showBrowserScreenForCurrentSession, which
            // creates the BrowserFragment and moves it to the front.
            SessionManager.getInstance().createSession(Source.USER_ENTERED, updatedUrlStr)
            return
        }

        val browserFragment = fragmentManager.findFragmentByTag(BrowserFragment.FRAGMENT_TAG) as? BrowserFragment ?:
                BrowserFragment.createForSession(sessionManager.currentSession)
        browserFragment.loadUrl(updatedUrlStr)

        if (!browserFragment.isVisible) {
            fragmentManager.beginTransaction()
                    .replace(R.id.container, browserFragment, BrowserFragment.FRAGMENT_TAG)
                    .addToBackStack(null)
                    .commit()
        }
```
However, there were some non-trivial issues.

In our code, I think we've been "globally" accessing BrowserFragment via findFragmentsByTag. However, this will unexpectedly return null after home is shown because the back stack is cleared when the home screen is opened. Therefore, we'll create a new BrowserFragment each time the home screen is shown. For an unknown reason, the old BrowserFragments are not being garbage collected and neither are the old WebViews contained within.

Another bug with this code is that we're created a new BrowserFragment and then calling `loadUrl` on it. This doesn't work because we can only load a url when the view hierarchy is inflated so the WebView is non-null – this is not true immediately after a fragment is created.

Some solutions that are complicated and it's hard to identify the side effects of:
- Move the WebView lifecycle outside the BrowserFragment (e.g. add it dynamically)
- Keep a global BrowserFragment reference (which contains a single reference to WebView) and re-use that

These are non-trivial so I'm wondering if this is approaching yak shaving territory but this BrowserFragment code is quite complicated so I can't tell if there's an easy fix.

**Comment by mcomella** [comment]
> For an unknown reason, the old BrowserFragments are not being garbage collected and neither are the old WebViews contained within.

It turns out this is a full blown memory leak: I filed #785. This is making it difficult to fix this bug: the only solution without fixing the memory leak is to pull the WebView out of BrowserFragment and into MainActivity, re-using the view there.

**Comment by mcomella** [comment]
I fixed #785 so now we can build on top of that to make sure our WebView instances are getting GC'd as necessary.

**Comment by mcomella** [comment]
Next steps:
- Fix [patch from previous comments](https://github.com/mozilla-mobile/firefox-tv/issues/507#issuecomment-379385704): make loadUrl work correctly, ensure there are no unwelcome side effects
- Extract method as separate method in `ScreenController` (for re-use)
- Call this method from `onNewIntent` and `handleIntent` (probably bring one layer of abstraction down from SessionManager to ScreenController/MainActivity

**Comment by mcomella** [comment]
@Sdaswani I would say one to two days.

**Comment by Sdaswani** [comment]
Thanks @mcomella . @bbinto just to note that 2.1 is still ongoing so the 3.0 schedule may get impacted.

**Comment by mcomella** [comment]
Follow-ups are #654, #793, #794, #795: this code is really crufty!
