### ISSUE TITLE
Navigating below bottom row of buttons leads to no buttons being selected

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#549]
A button (or the url text) should always be selected.

**Comment by liuche** [comment]
@lime124 what should happen if the user is on the bottom row of buttons, and tries to move "down" - should this take them back to the top row of buttons, or should the same button stay highlighted?

**Comment by liuche** [comment]
@lime124  a few questions about how button navigation should work:

- When at the bottom-most row, trying to go further down shouldn't do anything (because you are already at the bottom)
- When at the right-most button on the top row (Turbo mode button), and you hit "right", should this allow you to go to the next row (home button) or should that not do anything (and you stay on Turbo mode)?

**Comment by lime124** [comment]
@liuche 
the overall premise that something should always be selected is correct. 
- the up/down buttons should not loop back around e.g. on the top row, pressing down goes to the bottom row, pressing down again does nothing (and vice versa with up)
- hitting right/left should go to the next item in the row. if it's the last item on the top row, pressing right should jump down to the home button (like reading text) and vice versa with left. if it's the last item on the bottom row or the first item on the top row, it doesn't loop.

I just happened to notice that the tiles on the home screen don't follow this patter either ( I was hoping to say 'do it like that' :) )

**Comment by mcomella** [comment]
fwiw, navigating in loops could potentially be confusing for a11y users (e.g. looping from bottom to top). I think what Tif describes seems okay but I'm not expert.
