### ISSUE TITLE
Pinned Youtube TV *video* Don't Have A Screenshot

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#585]
1. Go to youtube.com/tv
2. Pin a specific video
3. Visit home screen

The pinned video has no screen shot in it's tile.

**Comment by mcomella** [comment]
Screenshots are writing into Android's drawing cache. It's possible the video is using a different rendering pipeline which doesn't write into the drawing cache and it's impossible to take a screenshot of.

It could also be that youtube is running in our fullscreen mode, which runs in a different view that we'd have to take a screenshot of instead.

**Comment by Sdaswani** [comment]
@lime124 should we just special case YT videos and use the same icon we use for the pinned tile?

**Comment by mcomella** [comment]
If this is non-trivial: we should use the placeholder. We may get screenshots that are all white from the browser, in which case we should detect it and not store the screenshot, so the placeholder will be used instead.

**Comment by mcomella** [comment]
Debug notes:
- The video screenshots are full transparency, not white. This is as detectable as white. This happens as soon as they're taken
- Taking a screenshot with the Youtube controls visible and video not playing will display the controls in the screenshot
- Taking a screenshot with the Youtube controls visible and video playing gets a raw screenshot with the controls over the transparency (i.e. video is not present). However, compressing this particular bitmap takes a long time and locks the screenshots files (blocking the custom home tiles from being shown if the user goes to the home screen from the video) until it completes, nevermind the CPU cost. We may be able to fix this by not using WebP, but there will be more artifacts in the images we store (though it probably doesn't matter since we shrink them so much anyway).

TODO:
- Test with Vimeo to see if it can also reproduce
- See if the Layout inspector can see the video
- If vimeo can repro, is there a way to figure out where the video is being rendered? Maybe it's a separate hardware accelerated view controlled by AmazonWebView that we can access
- File a bug for the thread block issue
- Come up with solution

**Comment by mcomella** [comment]
- Vimeo shows a black screen if not fullscreened. If fullscreened, it's a white screenshot. If I take a screenshot of the fullscreened view, it's their backfill, not the video (see screenshot). I filed #611 for us to consider always taking screenshots of the fullscreen view when available.
- The UI layout inspector shows a black screen: I expect we won't be able to capture a video screenshot in the ways I've previously considered – we'll have to find out if we can get a reference to the video render buffer or something. It's probably not worth it.

I think the solution here would be to do what we originally suggested: detect bad screenshots (all one color) and drop them on the floor. This will fall back to a placeholder #599.

Vimeo backfill screenshot:
![screen shot 2018-03-07 at 13 30 21](https://user-images.githubusercontent.com/759372/37119312-ce5672f6-220b-11e8-8bff-61b1fd4dc80c.png)

**Comment by Sdaswani** [comment]
Agree with the solution - detect empty picture and go to default.
