### ISSUE TITLE
SUMO article for v2.0

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#595]

**Comment by liuche** [comment]
Pinged Joni, will update with link here.

**Comment by liuche** [comment]
Joni has finished the following:
Turbo mode: https://support.mozilla.org/en-US/kb/turn-turbo-mode-or-firefox-fire-tv
Clear cookies/site data: https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox-fire-tv
and will finish Pinning/Removing by the end of the day 3/12.

And the main page is here: https://support.mozilla.org/en-US/kb/firefox-fire-tv

**Comment by liuche** [comment]
Joni, here are some screenshots for you:

Turbo mode onboarding screen (default selection is "keep turbo mode on" but this can be changed by the user on this screen):
![turbo-onboarding](https://user-images.githubusercontent.com/1082253/37306491-25ba889c-25f5-11e8-954f-1260511a8380.png)

Home tile with menu "hint" icon (on Youtube tile) - this tells the user they can click menu to open a context menu:
![hometile-menu](https://user-images.githubusercontent.com/1082253/37306526-36248ce6-25f5-11e8-94ea-7b5c88e077e4.png)

Context menu to remove the site focused when clicking "menu":
![hometile-remove](https://user-images.githubusercontent.com/1082253/37306555-4aae39fa-25f5-11e8-9cba-11450b6d2af7.png)

Overlay (site not pinned, turbo mode enabled):
![overlay](https://user-images.githubusercontent.com/1082253/37306575-5e725304-25f5-11e8-87cf-40d5a1132fce.png)

Pinning a site:
![pinning](https://user-images.githubusercontent.com/1082253/37306621-7e92789e-25f5-11e8-8eb1-329ac1156b28.png)

Home screen with the new pinned site + screenshot:
![new-tile-with-screenshot](https://user-images.githubusercontent.com/1082253/37306629-85b797f8-25f5-11e8-8b1c-f6d26306ce02.png)

Unpinning a site from the overlay:
![unpinning](https://user-images.githubusercontent.com/1082253/37306642-8fb79708-25f5-11e8-8d3a-4518a7d00cda.png)

Also as context (not specifically related to pinning), this is the overlay page with both the site pinned and turbo mode enabled:
![example-pinned-and-turbo](https://user-images.githubusercontent.com/1082253/37306676-adc509c4-25f5-11e8-8ff8-463d9ae9b19c.png)

And here is one with the an unpinned site, turbo mode disabled:
![example-no-pin-no-turbo](https://user-images.githubusercontent.com/1082253/37306704-c997e964-25f5-11e8-9d16-11176fe19a00.png)

**Comment by jonisavage** [comment]
Thank you, liuche. I've updated the article. Please let me know if we need any changes.

**Comment by liuche** [comment]
@jonisavage just two small changes:

* We can't actually "unpin" from the home screen (my screenshots might have been a little confusing). You can only remove (which is what you described in the "Remove a site" section). So the section about "Pin or unpin" should only have the "From a web page" section below it (and maybe instructions on opening a web page).

* For the icons, the blue background only indicates that the icon is selected - so the last two screenshots in the list have the pinned/unpinned background color (which is a subtle dark gray for pinned, and just black for unpinned). The blue background on those two items is really because my cursor is still on that icon so I could screenshot the confirmation toast.

**Comment by jonisavage** [comment]
Got it, thanks for the clarification. I've updated the article so that pinning/unpinning happens when the page is open and clarified that the blue background means the pin is selected.

**Comment by liuche** [comment]
Looked over the new SUMO article and it looks good, thanks Joni. Closing this!
