### ISSUE TITLE
Fandango default tile not opening page

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla-mobile/firefox-tv#613]
As seen in testing version 1.4.0.5:

Selecting the Fandango tile on the homepage tries to open https://fandango.com.  The page does not open with the connection timing out.  Same response if the address is entered into the address field in the overlay.

The page will open if https://www.fandango.com is entered into the address field in the overlay.

**Comment by bkmunar** [comment]
This sounds like we just have to edit the json, yeah? @mcomella

**Comment by Sdaswani** [comment]
Yes @bkmunar - that’s be only instance of fandango.com in the app, I bet.

**Comment by mcomella** [comment]
> This sounds like we just have to edit the json, yeah? @mcomella

This and IMDB were upgraded to HTTPS in https://github.com/mozilla-mobile/firefox-tv/commit/c0c913460b7e208b6b1fc6db8041e53bdc176183#diff-30c327b7444012e4c8b3f98dde94ed9a to make the "Pin/unpin" site work correctly. However, upgrading to HTTPS isn't as simple as adding an S (as we've noticed since https://fandango.com doesn't have a fine host). For example, [HTTPSEverywhere doesn't force upgrade fandango atm](https://www.eff.org/https-everywhere/atlas/domains/fandango.com.html).

@Sdaswani @bbinto How did we get the original URLs? If they came from those properties, I think we should use the ones they gave us, not redirect to "...www.fandango..." because it's possible something that can change on their server configuration and break our app. That being said, switching to http may break Pin/unpin for these sites (again).

**Comment by mcomella** [comment]
Options:
1. We ship http. This is less secure for users (e.g. if the site doesn't upgrade them to https, which they do now, or the user's connection is intercepted before it escalates to https) but it's more likely that the websites will always continue to work
1. We ship https: more secure but server configuration could break us

I'm more concerned about fandango than imdb because HTTPS doesn't support it, but now that I've made a fuss, maybe keeping users secure on default websites is more important than making sure the tiles always work, considering that we can just ship an update, or they can type in a URL to get the http version anyway.
