### ISSUE TITLE
[1304] Update Settings

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/firefox-tv#689]
**Why/User Benefit**
- Enable users to access settings in less clicks
- Make it easier for users to understand settings and choices

**What**
- Settings is a channel on the homepage
- All individual settings are a pin on the homepage and open up to a detail view
- Detail view includes:
-- header area with a title and a back button
-- content area that supports:
--- text only (eg about page)
--- text + buttons (eg clear cookies example above)
--- text + toggles (eg send usage and data)
--- list + toggles (eg homescreen customization)
-- The back button uses the same icon as the Fire TV remote so that we build on top of what users already are familiar with.

**Acceptance Criteria (how do I know when I’m done?)**
- Probes on all toggles
- Probe to enter settings

**KPI/Data**
- How many of these people change their settings (toggle)
- How many of the default settings are (not) changed by the user

**Comment by bbinto** [comment]
@aminalhazwani -- would you mind providing some ideas here so eng can estimate. (no mocks needed right now) -- we think it doesn't have to be a big change, just some clean-up

**Comment by aminalhazwani** [comment]
@bbinto I am happy that you asked! The current settings page includes:

- Send usage data, which is a control/checkbox
- About, which opens a subview
- Privacy notice, which is a link to a subview/webview
- Clear all cookies and site data, which opens a modal

We could maintain the same layout and navigation, bringing in also some of learning from the Pocket feed, and invest more into the interaction and overall experience.

Every setting could be a little card that could grow in size and change the background if the user selects it. The same card could expand to a larger view if the users presses it. The expanded area could be used to suit texts, list controls (checkboxes/radios/switches), and all the components necessary to let users customize their browsing experience. The flexibility of this pattern would allow the the settings page to be easily extended in the future.

In the image below you can see the main settings view with the first card - send usage and stats - highlighted.  If selected it grows to a bigger area where you can read more and toggle on and off the switches.

<img width="512" alt="screen shot 2018-04-23 at 6 41 29 pm" src="https://user-images.githubusercontent.com/1721875/39140836-13c394e2-4726-11e8-8a6e-e9844f7e4269.png">

The other example - about firefox - can displays the same text that we currently feature in the app. As mentioned the same pattern could be extended to parental control, privacy notice, cookies and site data and more to come.

**Comment by bbinto** [comment]
#1189 should/can be considered to be fixed with this update revamp

**Comment by aminalhazwani** [comment]
Hello! Here's an update for the setting page, the homescreen design now includes a "channel" for settings, and every setting links to a detail view, more details on the channel design will be posted to the specific issue.

<img width="861" alt="image" src="https://user-images.githubusercontent.com/1721875/47297585-bbe7fb80-d615-11e8-8856-56ba940ab27a.png">

Back to detail view: every view features a header area and a content area. The header includes a title and a back button. The back button uses the same icon as the Fire TV remote so that we build on top of what users already are familiar with.

<img width="619" alt="image" src="https://user-images.githubusercontent.com/1721875/47298441-15e9c080-d618-11e8-9c25-27db6275eb46.png">

The focus moves within the view based on what's "focusable".

<img width="1370" alt="image" src="https://user-images.githubusercontent.com/1721875/47298531-59442f00-d618-11e8-98df-632f74e9ebc3.png">

Content area can include:
- text only (eg about page)
- text + buttons (eg clear cookies example above)
- text + toggles (eg send usage and data)
- list + toggles (eg homescreen customization)

For example this is how _text only_ might look:

<img width="635" alt="image" src="https://user-images.githubusercontent.com/1721875/47298734-cf489600-d618-11e8-9bbd-eef24c6e7942.png">

And this is how _text + toggles_ might look. On the left you see focus on the back button, on the right you see focus on the _text + toggle_.

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/1721875/47298694-b809a880-d618-11e8-9e18-1d6d47d2045d.png">

This system enable us to extend the app settings based on the possible future requirements/user needs. In the example below you can find a possible Pocket setting for hiding the recommendations from the homescreen, a possible setting for restoring the bundled titles, and a possible setting for customizing the homescreen.

<img width="1361" alt="image" src="https://user-images.githubusercontent.com/1721875/47299231-0ec3b200-d61a-11e8-9728-e20f648a6f53.png">

As always the specs can be found here https://github.com/mozilla-mobile/firefox-tv/wiki/Design#mocks-with-a-web-interface.

@athomasmoz let me know if this comment is enough or if we should also update https://github.com/mozilla-mobile/firefox-tv/issues/689#issue-306038900, thanks!

**Comment by athomasmoz** [comment]
Thanks @aminalhazwani ! I updated the description to match.

**Comment by liuche** [comment]
@brampitoyo can you take a quick look at these mocks if you get a chance, and let me know if they still seem reasonable to you? I think they look fine (for the screens that we already have), but I'll need some **icons**.

Will also check with Meridel about these strings (but for the most part they seem fine). @athomasmoz do the strings seem fine with you at a first glance? https://github.com/mozilla-mobile/firefox-tv/wiki/Design#mocks-with-a-web-interface

**Comment by liuche** [comment]
Hi @MeridelW, assigned you here to this - please feel free to comment on any changes to the strings as you see reasonable!

**Comment by athomasmoz** [comment]
@liuche Yes, I don't see many changes in the strings. However, we may want to keep the full About page text. I'm not sure if hiding the 2nd half of user rights on the initial view is a good idea. 

Another thought - is it worth changing the strings within the context of this story? They're minor wording changes and I'm not sure if there's enough value to warrant asking for help localizing them.

**Comment by MeridelW** [comment]
Will be sending string edits shortly!

**Comment by MeridelW** [comment]
Copy edits noted on screenshots in this folder: https://drive.google.com/open?id=1mR8oc3RFZU0OjHoNpBV3WzX2O4ABN8nf. Apologies for formatting—it was difficult to figure out how to capture my comments in the files. 

I have questions out to legal and Nick Chapman, as noted in the comments, about two issues. Will update file once I have those answers and let you know.

@brampitoyo please let me know if you want to meet! Some of my comments are open questions...

**Comment by liuche** [comment]
Thanks @MeridelW ! I'll take a look at those strings! And good point about the Pocket string - we've heard from user studies that they also get the impression those videos were "recommended by Pocket" completely separate of Mozilla, and they seem like ads.

**Comment by liuche** [comment]
A few things I need from you @brampitoyo:
* New icons for the settings tiles
* Icon for the remote back button
* Sizing of the Settings tiles as you navigate past them - right now the zoom seems not very noticeable, should I just make them grow bigger?

I still have to fix a few things (like focus change), but feedback is welcome!

Here's the apk:
https://drive.google.com/open?id=1_bl14w_lUZCXtRDPeiyah7moY6SZ6cA-

**Comment by brampitoyo** [comment]
Thanks @liuche for summarising what you need from me!

> New icons for the settings tiles

I had a look at Amin’s specs. These new icons are merely existing SVGs that were scaled up 200%, to 48x48dp.

The canonical link for these icons is https://design.firefox.com/icons/viewer/# – under the “Android” tab.

The icons are called:
* Data Collection
* Info
* Delete
* Globe

> Icon for the remote back button

This is an Amazon asset, so it’s not stored in Photon. Find it here: https://cl.ly/62edd6a630e3/hardware-remote-back.svg

I also have other remote button assets and am happy to post them if required :-)

> Sizing of the Settings tiles as you navigate past them - right now the zoom seems not very noticeable, should I just make them grow bigger?

It seems as if Amin had designed a focus ring to emphasise currently selected item, without doinng any zooming. I would advocate using both the focus ring and a zoom, just to make things super clear.

The scale I would recommend is:

* Non-selected item: 172x96
* Currently selected item: scale up 125%: 215x120

We can also fade all non-selected sections, but let’s stick with this for now.

**Comment by liuche** [comment]
Remaining work:
* Incorporate new icons (back + settings)
* Add focus ring + suggested sizing
* Fix tests

Optional:
* Move Turbo mode out (or file separate bug)

**Comment by athomasmoz** [comment]
@liuche one more addition to the remaining work. There is one SUMO article that mentions settings, which will need to be updated
https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox-fire-tv

**Comment by liuche** [comment]
@brampitoyo sorry, one last thing: I got the "back" asset but it has a circle around it that doesn't look right. Could you get me another asset with the back icon, but without the ring?

**Comment by liuche** [comment]
@jonisavage could you update the new Clear data flow? We'll remove the settings icon in this bug, and move all the settings to a "channel" at the bottom of the navigation overlay. (We'll also move Turbo Mode in #2019)

We plan to release this at the end of this sprint (which will probably be ~4/17).

**Comment by brampitoyo** [comment]
@liuche wrote:
> I got the "back" asset but it has a circle around it that doesn't look right. Could you get me another asset with the back icon, but without the ring?

Yes. Sorry about giving you the back icon with the ring. That ring was only meant as a representation of a specific button on the remote, and not a generic back action.

This is the correct icon: https://cl.ly/d1bd0a1f9aaa/Fire%20TV%20Back.svg

**Comment by jonisavage** [comment]
> @liuche one more addition to the remaining work. There is one SUMO article that mentions settings, which will need to be updated
> https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox-fire-tv



> @jonisavage could you update the new Clear data flow? We'll remove the settings icon in this bug, and move all the settings to a "channel" at the bottom of the navigation overlay. (We'll also move Turbo Mode in #2019)
> 
Thanks for the clear screenshots, @liuche . We've updated these articles to reflect the new Settings channel:

https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox-fire-tv
https://support.mozilla.org/en-US/kb/send-usage-data-firefox-mobile-devices

We'll keep an eye out for the Turbo Mode change so we can update the articles appropriately.
