### ISSUE TITLE
Add "About" text describing what Firefox TV is for

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#718]
In Focus, we have an **About** page in Settings that describes what Focus is for. We should have one for Firefox TV (instead of just a place to list licenses as in #691 ). Talked to @lime124 and we can add that right above the <you rights> text in the "About" item.

Needs some direction from @bbinto and maybe marketing.

```
Firefox Focus puts you in control.
Use it as a private browser:
* Search and browse right in the app
* Block trackers (or update settings to allow trackers)
* Erase to delete cookies as well as search and browsing history
Firefox Focus is produced by Mozilla. Our mission is to foster a healthy, open Internet.
Learn more
```

**Comment by bbinto** [comment]
I think that's a clear case for the amazing @BrianNJones :)

**Comment by BrianNJones** [comment]
For this to be valuable content, let's get to clarity about the use cases we want to highlight here (privacy? video access? general content consumption via TV?).
- Existing Focus content highlights "private browser" functionality, content that doesn't necessarily make sense in the Firefox for Fire TV context. 
-Amazon app store content highlights ability to watch videos (content dates from 12/17, prior to any visibility into how users were actually using the app)
-(Worth noting that desktop and non-Focus mobile products don't include this type of in-product or in-app content at all.)

**Comment by mcomella** [comment]
I love that we have the opportunity to champion the open web on the TV platform: what if there were more websites like youtube.com/tv that felt it was valuable to tailor their content to a TV interface? What if we could standardize TV browsing techniques (e.g. is a dpad really the best interface?) and APIs to make TV browsing a desirable experience that solves real user needs? (Since it can be sub-par right now...) There was a transition from desktop -> mobile and perhaps there will be a transition where a TV could become a primary interface for some user needs.

TV interfaces haven't been big historically, but I wonder if that was just limitations around the hardware (e.g. Smart TVs don't get replaced often but now we're on a dedicated computing device that's easier to upgrade).

**Comment by liuche** [comment]
I agree with Brian, @bbinto what are the things that we want to highlight "about" Firefox TV? Can you give some guidance/priority on key features of our product? I like what mcomella is highlighting as the future of "a browser for tv", but if we want to update this text in the near future we can also highlight what features we have:

* ad-blocking Turbo mode
* Youtube access
* Ability to clear history (though not in the same way Focus is)
* Easily save and access videos
* Pocket recommendations?

That being said, I'd love to see this diverge further from Focus, because they are very different platforms!

**Comment by Sdaswani** [comment]
@bbinto to answer @BrianNJones qeustions here: https://github.com/mozilla-mobile/firefox-tv/issues/718#issuecomment-375707903

**Comment by bbinto** [comment]
Low priority for now, I’ll work with marketing and Brian to in the future. No immediate action needed right now.P3On Mar 27, 2018, at 12:42 PM, liuche <notifications@github.com> wrote:Assigned #718 to @bbinto.—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by athomasmoz** [comment]
Closing as low priority
