### ISSUE TITLE
[Home] Handle tile "removal" now that menu button is overloaded

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#782]
With the overlay, the menu button will close the overlay, but that means we can't also use it for deleting tiles anymore.

Some options we discussed were:
* Remove "remove" - don't allow removing for this release
* Long-press "select" button to trigger remove context menu
* Add new "doorhanger" UI to add remove option

Whichever option we choose, we should also revisit it in a sebsequent release (maybe 3.1).

**Comment by mcomella** [comment]
iiuc, the behavior would be that the user long-presses the home button to unpin a top site.

@aminalhazwani General concerns that can be overruled with further research 😄:
- Accessibility with VoiceView overrides some of the button behavior so we should make sure there aren't conflicts. I think long-pressing home opens the VoiceView settings.
- Without a11y, long-pressing the home button from the device home screen displays a system menu (e.g. Settings, apps, put device to sleep): does this also happen when you're already in an application?
- To me as an Android user, the home button is conceptually a system button: it seems strange that any interactions with it would affect the app

If we were thinking about long-pressing the menu button:
- Long-pressing the menu button in a11y switches between VoiceView modes ("review" and the spatial navigation mode) - but maybe it's okay to remove this functionality for a few weeks for a subset of our users?

Since we'd probably want to fix this in the next sprint (after two weeks), it might be okay to have some shortcomings.

**Comment by lime124** [comment]
@aminalhazwani thanks for jumping on this so quickly after your PTO (welcome back!)

The design rationale for double tap vs long press totally makes sense and I agree. 

I echo mcomella's concerns about using the home button as the long press. I agree it should be reserved for the system (though I'm sure there are examples of apps breaking this). 

The menu seems plausible, but it seems like it's reserved for a11y functionality. It's also worth thinking more about the potential of accidentally closing the overlay when wanting to remove a tile because you didn't press long enough and vice versa. 

Were you able to explore other buttons on the remote? Are any of those a good candidate? 

Overall, I think this is a good solution and hopefully something that can be pretty easily implemented. When I talked to liuche this AM, she mentioned it might be a bit hard/not possible to include a graphic in a string and/or the toast. So we might have to iterate a bit on the formatting and the final string (with brjones of course!). 

@liuche were you able to confirm if we can include an icon in a toast before your flight?

**Comment by aminalhazwani** [comment]
@mcomella ops, thinking too much on the homescreen I wrote Home button instead of Menu button, sorry!

@lime124 if it's not possible to include a graphic in the chip we could use the unicode symbol `☰`. My rational there was to display what users see on their remote rather than describing it.

Anyway, here is an overview of the buttons and their resulting actions. 

### While on FireTV Homescreen *without* VoiceView enable:

**Menu button**
- Long press Menu button while on the navigation: no result
- Long press Menu button while on the slideshow: no result
- Long press Menu button while on recent app: after releasing the button the side menu 'Options' shows up with two options (More Into, Remove from Recent). Same result with different options if you long press on the homescreen rows below the recent app row.

![long-press-menu-button](https://user-images.githubusercontent.com/1721875/38500803-bcbd2070-3c0b-11e8-9faa-dcfe56f55a26.jpg)

**Home button**
- Long press on Home button: shows clock and shortcuts (Apps, Sleep, Settings).

![long-press-home-button](https://user-images.githubusercontent.com/1721875/38500809-c37f9654-3c0b-11e8-916b-3906d7b676de.jpg)

**Select button**
- Long press Select button on navigation, slideshow, rows: no result.

### While on FireTV Homescreen *with* VoiceView enable:

**Menu button**
- Long press on Menu button: toggle Review Mode.

**Home button**
- Long press on Home button: shows clock and shortcuts (Apps, Sleep, Settings).

**Select button**
- Long press on Select button: if Review Mode is enable exit the tutorial.

### While inside Firefox for FireTV *without* VoiceView enable:

**Menu button**
- Long press on Menu button: no result (but when you release the button it triggers the action, eg if you're long pressing on a tile it prompts the remove button)

**Home button**
- Long press on Home button: shows clock and shortcuts (Apps, Sleep, Settings). In answer to your question @mcomella.

**Select button**
- Long press on Select button: no result (but when you release the button it triggers the action, eg if you're long pressing on a tile it goes to the website).

### While inside Firefox *with* VoiceView enable:

**Menu button**
- Long press on Menu button: toggle Review Mode.

**Home button**
- Long press on Home button: shows clock and shortcuts (Apps, Sleep, Settings).

**Select button**
- Long press on Select button: no result (but when you release the button it triggers the action, eg if you're long pressing on a tile it goes to the website).

Some findings: 
- You can enable VoiceView by long pressing the Back and Menu button together for 2 seconds.
- If you try to enable VoiceView while browsing it also triggers the action related to one of the buttons necessary to enable it (either Back or Show Menu). Moreover the Menu button is not responding when VoiceView is enabled. In order to display the overlay menu you need to double-press the menu button.

So, where does this leave us? 

a) We could use the long-press on the Menu button to remove a pinned website if VoiceView is not enable and long-press the Back button if VoiceView is enabled. If we opt for this solution we have to, first make the chip/snackbar sliding in from the bottom of the TV dismissable only by user action because if it auto-dismiss we cannot be sure that a user with VoiceView enabled gets to the snackbar in time. Second, we have to make sure that when you release the long-pressed button the single-press action isn't triggered (as mentioned above).

b) What about the backward, play/pause and forward button? Do we have access to those buttons outside a video mode? Probably the one closer to the remove metaphor is the Backward button and we could direct users to long-press on that button to let them remove a top-site.

c) Long-press the Select button. It doesn't seem to have any function when VoiceView is enabled. It's harder to explain how to use it (no symbol) but we could design something more visual. It's also more semantically related to the type of action that a user might want to do (eg remove a pinned website). Single-press Select triggers the first action, long-press triggers the secondary action, in our case it shows related options (eg remove a pinned website, and maybe others in the future). Also in this case we have to make sure that when you release the long-pressed button the single-press action isn't triggered.

If we have enough time I would suggest to work on option c) as it doesn't bring conflicts with VoiceView and it's future-friendly.

**Comment by lime124** [comment]
Thanks for the very through analysis Amin! I would love to hear what @mcomella and @liuche think about the options.

**Comment by liuche** [comment]
For (c), I like the primary/secondary actions being tied together into a single button. It feels very natural because that's the main "action" button anyway. The hardest part there will be getting a string that explains the "center" or "select" button, but implementation-wise it isn't hard.

From an engineering perspective, here are the difficult parts:
* Substituting an image into string. I didn't get a chance to get a working prototype (but we might also have to do things like set a size, not sure if should be svg or png).
However, if we use the "select" button, we might be able to get away with just using "Long press to Unpin" (or long click), because there aren't any other plausible ways to "long press" a tile.
* Toast should be fine, I think (setting a focus listener on the recyclerview), but I wonder if we should stop showing that toast/hint after a certain point? (e.g., seen it 5 times)

**Comment by mcomella** [comment]
(c) is the easiest from an engineering perspective so 👍! From a design perspective, I like that it doesn't conflict with a11y and that semantically the actions are linked. My hesitation is that Android's guidelines have moved away from long-press for anything but multi-select mode to avoid hidden functionality. But given the time constraints we have from both an eng and a design perspective and that long-press for context menu is an existing (but outdated) convention, I think it will work well.

(b) is also easy from an eng perspective but I think it could be confusing for users to use the media buttons for anything that isn't actually media (or game) related.

@aminalhazwani Do you want us to move forward with (c) for this bug?

**Comment by lime124** [comment]
Thanks mcomella and liuche for the thoughts! Let's go with c - I think it's the best option and everyone seems to have agreed on that too :) 

The few outstanding things I see are: 

1. Finalize a string for the toast - @BrianNJones for help
2. Depending on the string we may or may not need an icon or graphic (if that's feasible)
3. Ensure long press in app does nothing outside of this context. As Amin points out, it currently completes the action.
4. Determine at what point the toast disappears (or is it always present). - @aminalhazwani did you have a thought on this already?

Did I miss anything? Thanks!

**Comment by lime124** [comment]
Something I just remembered - @liuche @mcomella I think one or both of you mentioned that for this first version we won't be able to remove the Pocket Tile? If that is the case, we should make sure to handle that as well. I would think one step would be to note show the toast when Pocket is selected and the other would be to show a message if the person does try to long press on the Pocket tile.

**Comment by aminalhazwani** [comment]
Thank you all for the feedback! 

We could display the toast and dismiss it after a user actually unpins a website or after a 5 seconds timeout. We could also show the toast 3 times at launch.

![fftv - chip unpin top site](https://user-images.githubusercontent.com/1721875/38560442-f0df110e-3cd5-11e8-82a1-d84628a4f956.jpg)

If a user tries to unpin Pocket Videos we could show a toast, same position different text. It would probably make sense to craft the message in order to let users know that this action is not possible only for the time being.

![fftv - unpin pocket videos](https://user-images.githubusercontent.com/1721875/38560569-37cc2cb4-3cd6-11e8-8349-694c80c5f4d4.jpg)

Alternatively we could display a classic snackbar that is only dismissable by the user.

![fftv - snackback](https://user-images.githubusercontent.com/1721875/38560939-14636b9c-3cd7-11e8-95cf-a24e94d75af2.jpg)

**Comment by lime124** [comment]
i'm curious how much harder it would be to do the dismissable toast over the original proposal. @liuche @mcomella ?

@aminalhazwani let's wait on that answer before digging in more to some IxD questions I have on that one.

**Comment by bkmunar** [comment]
I'd like to pick this up once UX is finalized :)

**Comment by mcomella** [comment]
> I think one or both of you mentioned that for this first version we won't be able to remove the Pocket Tile?

I think that's only if we split the megatile into multiple tiles (i.e. so there isn't a single "Pocket" section to click on): what did we decide to do for the megatile? Can we update #774 with the details?

> i'm curious how much harder it would be to do the dismissable toast over the original proposal. 

We'd have to build it ourselves so it'd take more effort (whereas the toast is trivial): I'd rather spend the implementation effort on higher impact things (like our v2!). I'm also especially concerned that getting the dpad navigation right would be tricky. As a user, it also seems awkward to navigate to this toast in order to dismiss it (e.g. scrolling through multiple rows of tiles, especially if they need to scroll in from off screen).

**Comment by BrianNJones** [comment]
I don't think "long press" makes sense for something that's not a phone (or, put another way: "long press" is understood to be a phone screen convention). Existing style guides for Roku/Apple TV/etc don't weigh in. I'd like to establish this as a convention:

Press and hold <insert icon or button name> to <action>

So: Press and hold SELECT to unpin from homescreen

**Comment by aminalhazwani** [comment]
Thanks @BrianNJones!

**Comment by aminalhazwani** [comment]
I suggested an alternative method here https://github.com/mozilla-mobile/firefox-tv/issues/780#issuecomment-405954161 that might be more discoverable and helpful.

**Comment by aminalhazwani** [comment]
Uhm, I simply add a comment, I wonder why it says I unassigned Bryan 🤔
