### ISSUE TITLE
Add telemetry probe: unique tiles clicked per user per session

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#798]
Why: we want to know if our users use the app in a variety of ways or generally use it for a few experiences. This is an important baseline measurement in v2.1 for our homescreen redesign in v3.0, where we hope for users to use the app in a larger variety of ways.

**Comment by liuche** [comment]
Talked to Frank and from our discussion, per-session is much better than "forever". He also suggested that we could upload unique tileIds per session, obfuscating the bundled tiles with a client salt, but to get this into 2.1 per-session unique tile count should be fine.

**Comment by mcomella** [comment]
> Talked to Frank and from our discussion, per-session is much better than "forever".

@liuche Why is it better?

> He also suggested that we could upload unique tileIds per session, obfuscating the bundled tiles with a client salt,

I'm not sure what the value of this is over the count.

**Comment by mcomella** [comment]
@pocmo I'm adding a probe that needs to reset at the end of a session. The existing telemetry code starts and stops sessions in `onPause/onResume`, which seems wrong to me (e.g. a dialog could stop a session). Why did you choose to put them there instead of `onStart/onStop`?

**Comment by liuche** [comment]
Re: questions above:
* per-session vs forever
Frank said aggregating data over even a week was non-ideal because then the analysis is not very granular and can only provide insights into behavior at the weekly level (which could bucket many types of usage, e.g. visiting 1 website every day vs 1 website once a week are different usage patterns that would be helpful to differentiate on).

* Unique tileIds
This way you could see things across sessions like "people tend to visit the same set of websites always" vs "people visit different websites, but usually this particular number", and you could learn more about usage while still maintaining privacy of websites visited.
