### ISSUE TITLE
Tile placement according to users visits

### ISSUE THREAD

**Issue by IasonNissopoulos** [mozilla-mobile/firefox-tv#816]
## What
 Tiles are sorted according to the times the user has visited the site

## Why

- Less time for the user to find his most visited tiles, which goes in hand with the custom-pinned tiles logic.

- Better user access.

- Faster browsing.

## Positives 

- Faster browsing.

- UI look and feel won't change.
## How do I know when I’m done?
- When a tile's website gets more visits than another's, they switch places.
- Users can switch on/off this function (if it overpopulates the Settings menu, then not)

It should work like this : 

![first](https://user-images.githubusercontent.com/22798997/38783323-da943eb0-4108-11e8-89ac-a88ae46ccf31.png)
![real-second](https://user-images.githubusercontent.com/22798997/38783418-7c2e896e-410a-11e8-9df1-a6709991c154.png)

**Comment by IasonNissopoulos** [comment]
I am working on it.

**Comment by mcomella** [comment]
Thanks for the suggestion @IasonNissopoulos, we'll take a look at this in triage tomorrow.

I received an email saying you were also working on this (it seems that it may have been deleted). I just wanted to suggest you wait until our triage discussion before jumping in because we'll want to review this design and see how it fits in with the vision of the product: do we like it? Does it conflict with a future feature? Will this problem be solved in another way (see also #804)?

**Comment by IasonNissopoulos** [comment]
Thank you for the reply @mcomella, i will be waiting until your triage discussion before starting the integration.
I deleted the "Working on it" comment because i haven't started writing actual code, so i thought it might be misleading.

**Comment by mcomella** [comment]
@bbinto We missed triage today but Iason is waiting on our comment – do you have thoughts on what we'd want to do for this bug?

**Comment by bbinto** [comment]
Interesting ideas, @aminalhazwani -- what's your opinion about it?

**Comment by aminalhazwani** [comment]
@bbinto it's definitely something we could experiment with! We could probably leverage some of the experience that the New Tab team already has with the work on Top Sites, this is what they are using for sorting https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Places/Frecency_algorithm

I say experimenting because we have to consider the established procedural memory that users have when going to a specific tile eg Rotten Tomatoes is Down > Left > Left.

If we introduce this we could also think about promoting more the Pin feature so that the users homescreen can potentially be a great mix of customisation and personalisaiton.

**Comment by mcomella** [comment]
> I say experimenting because we have to consider the established procedural memory that users have when going to a specific tile eg Rotten Tomatoes is Down > Left > Left.

@aminalhazwani I think we've had discussions about this in the past with Firefox for Android's top tiles: perhaps there is some research or previous designer experience (e.g. Antlam or Tif) you can check in with before we start implementing? The Activity Stream team might have some thoughts too.

**Comment by liuche** [comment]
I think this is a great idea, but I think that we might want to wait on #575 first, because right now, there's no way to keep track of when a url has been last visited, and we should choose a single way to handle that, rather than building one here, and then having to support two later.

@aminalhazwani's point that people might rely on muscle memory to find tiles, and would have a harder time otherwise, is also something to consider.

AFAIK, @lime124 said in the past that we'd want to follow the Firefox top sites/activity stream pattern, which is:
* Top Sites are most frequently used (which is not necessarily most recently used)
* Pinned Sites don't move (although for TV right now, Pinned Sites is being used as a stopgap for not having history)

**Comment by aminalhazwani** [comment]
@mcomella @liuche thanks for feedback! I agree with what @liuche and @lime124 say

> we'd want to follow the Firefox top sites/activity stream pattern

if we don't have specific requirements and/or constraints on TV it makes sense that the way we sort Top Sites and Pinned Sites is the same as the other Firefox products

**Comment by athomasmoz** [comment]
Closing based on above comments. Agree that pinned sites should stay put, so users know where to find them. And this is a great approach to take when looking into history for the future.
