### ISSUE TITLE
[a11y] on Pocket video feed

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#827]
I forget how something like the Pocket header, which says "Pocket" but is generally not focusable, should be handled.

+any content descriptions for UI (that will also need to be localized)

**Comment by liuche** [comment]
When opening the Pocket video feed, it goes immediately to the feed and lists off what is in the feed. 

Some problems:
- [ ] The "help" button doesn't have any accessibility text just "button"
- [ ] In Review mode (where you can select non-selectable items, read by char/word/item), the "Recommended videos" header is read, but the Pocket logo isn't selectable (because it's not text)

**Comment by liuche** [comment]
Filed #1125 for the "help" button.
