### ISSUE TITLE
Figure out how to handle Release Notes translations

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#833]
From the Amazon UI:
> Note: Release notes are required for all provided translations. English (U.S.) will be used in all marketplaces where a translation has not been provided. 

The required languages (for now) are English, German, and French. I asked for translations on IRC and @Delphine mentions we shouldn't do it like this, outside the regular release process. This bug is to have a conversation about how we want to make this a regular process.

**Comment by Delphine** [comment]
Thanks for filing this Michael. I know you weren't previously aware of this since you didn't do the release process for Firefox TV before.

So I guess this explains why last time our usual l10n process was bypassed... I have to admit I'm extremely surprised that that was not explained to me when I clearly asked why that had happened in [this email thread](https://groups.google.com/a/mozilla.com/forum/#!msg/firefox-tv/95c2qfoPVik/uLjpQANnBgAJ) - and neither in the follow-up Github issue #728 

We can't just localize things like this out of process, and last minute (even if it's just one string). The best I can give you is a Machine Translation for French this time, and I'd like to request that these stop being taken care of this way, for both German and French. If we need to get release notes for each and every release in order to submit the app, then we'll have to work on getting that set-up correctly on our side. Issue #728 has proposals for that.

@mcomella: in the meantime, could you please confirm that all the strings needed for French are these ones please: 
* https://mcomella.pastebin.mozilla.org/9083381
* https://mcomella.pastebin.mozilla.org/9083382

(CC @gueroJeff and @bbinto  so we are all on the same page)

**Comment by Delphine** [comment]
Additional comments: 
* For the record: we don't localize Release Notes in any Mozilla product (not even Firefox desktop). 
* If "release notes" = "what's new" content in this case (which I think it is), we stopped doing it for any mobile product excluding Firefox for Android and Firefox for iOS, because it simply wasn't working.

I understand in this case you *need* to enter something in German and French fields in order to submit the app. Another "solution" would be to just paste in English, or MT the text in, I guess.

**Comment by mcomella** [comment]
The strings we need translated are:
```
    - Bug fixes
    - Updated Your Rights page
    - Improved cursor 
```

> If "release notes" = "what's new" content in this case (which I think it is)

tbh, I'm not sure how this field is used so that should perhaps be the first step in figuring out what we want to do with this field going forward.

Assigning Susheel so he's aware of this.

**Comment by Delphine** [comment]
Thanks Michael. I only caught up with Slack and saw the text has been sent to Sylvestre for French translation. Maybe you already received those?

**Comment by bbinto** [comment]
@Delphine - it's late in Europe now, would you mind giving it a quick translate? :)

It'd be great to be able to submit today and French is the only missing item on the list.

**Comment by Delphine** [comment]
Here's the French translation: 

- Correction de bugs
- Mise à jour de la page Droits de l’utilisateur
- Amélioration du curseur

Let's keep this issue open to agree on how we'll handle this in the future :) This doesn't look like it can scale at the moment. Thanks!

**Comment by mcomella** [comment]
I see this got backlogged but we don't have a process (automated or not) for handling how we translate these release notes: removing from triage so we can figure one out.

@bbinto Do we intend to just have employees translate for now? If so, can we explicitly specify who?

**Comment by mcomella** [comment]
Another thought: we may want to have consistency in how the notes are written ("Add" vs. "Added") so we could decide that through this process.

**Comment by bbinto** [comment]
@Sdaswani is talking to Amazon a publishing API.

**Comment by Sdaswani** [comment]
@haldeman99 is giving me details about the publishing API soon.

**Comment by liuche** [comment]
Since we tend to reuse the "bugfixes and stability" release notes, and Marketing/@lwa-moz makes sure we get copy when there are messages to handle, I think we can close this.

@athomasmoz is there more process that needs to happen around this? If so please feel free to reopen!
