### ISSUE TITLE
Standardize a Firefox TV design language

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#836]
### Why/User Benefit/User Problem
Users expect a delightful, consistent experience from their apps for:
- The device/platform they're using the app on
- The app across devices/platforms (e.g. Firefox on Desktop vs. Firefox mobile)

If the experience is inconsistent, users feel the product is of lower quality, are less delighted by it, and less forgiving of it.

### What / Requirements
Create a design language consistent with:
- Firefox
- Fire TV
- "Streaming devices"? from Brian Jones
- Android? The Fire TV uses Android APIs but is the design language Android? Do we plan to ship to Android TVs? If yes to either of these, we should consider the Android design language
- Other smart TVs? Do we plan to ship anywhere else?

### Acceptance Criteria (how do I know when I’m done?)
- We have a design language plan to apply when creating new features so that they are consistent with the platform requirements listed above

---

This conversation began in https://github.com/mozilla-mobile/firefox-tv/issues/769#issuecomment-382051070 and Brian and Amin suggested that we discuss this as a team to combine design with product possibilities.

**Comment by aminalhazwani** [comment]
I think @BrianNJones and I were mostly speaking of [copy style and rules](https://design.firefox.com/photon/copy/capitalization.html) because this is where our products currently differ the most and where we are starting to raise questions like "Is Fire TV Android or something else?". But I guess that this issue is still valid and aligns well with work that the Design System team and Photon are trying to do!

**Comment by athomasmoz** [comment]
Closing as lower priority for now
