### ISSUE TITLE
Newly added tiles are cropped off-screen and can't be scrolled into view

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/firefox-tv#893]
Testing via master 0b63a732288395d2b8ec9cb9d8a63c01da650e64

When a new tile is added, it is cropped off-screen out of view and can't be scrolled into view

Probably a regression from the Pocket 'mega-tile' landing.

**Comment by mcomella** [comment]
@aminalhazwani Do you have thoughts on how we can address this?

**Comment by aminalhazwani** [comment]
On the left a screenshot taken from the TV, on the right the desired result

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/1721875/44142607-0373f41a-a081-11e8-94ec-226d8f8406ec.png">

We could set space and grid as per mocks so that the last row of pinned tiles is cut out and suggests. But this might be not enough, we could also add a tooltip that let users know that newly pinned sites are at the bottom of the screen. But first let me export the mocks to the web inspector!

**Comment by aminalhazwani** [comment]
I added the web inspector to Google Drive, all details on how to can be found here https://github.com/mozilla-mobile/firefox-tv/wiki/Design#mocks-with-a-web-interface

**Comment by Baron-Severin** [comment]
@aminalhazwani I'm not sure how well this comes across in the screenshot, but on the TV I'm not sure this fixes our problem.  The tiles being cut off on the bottom aren't immediately noticeable, and the extra space between the URL bar and Pocket seems a bit strange.  Is there any way we can move this the other direction, to have the third row of tiles partially show on screen?

![tv](https://user-images.githubusercontent.com/13170306/45327008-aa85dc80-b50a-11e8-9368-cc1bb316c65a.png)

**Comment by aminalhazwani** [comment]
Thanks for the feedback @Baron-Severin! I initially tried to squish everything so that we could show a third row but it wasn't enough to make the row visible above the overscan (see https://developer.amazon.com/docs/fire-tv/design-and-user-experience-guidelines.html#overscan-and-the-safe-zone for context)

![pocket tile](https://user-images.githubusercontent.com/1721875/45364340-2ef36080-b5da-11e8-8ab8-ff37d9e48ba2.jpg)

**Comment by aminalhazwani** [comment]
For now we could keep this quick solution and for the next release we try to come up with a better approach 🙂

**Comment by Baron-Severin** [comment]
@aminalhazwani 👍 I'll get it done.
