### ISSUE TITLE
Combined overlay: specify dpad navigation

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#906]
### Why/User Benefit/User Problem
Right now dpad navigation does whatever Android does by default: it's not great. Here are some problems:
1) Pressing down from Pocket tile goes to third home tile
2) Pressing up from url bar sometimes goes to settings
3) Selecting a button that is then disabled (e.g. press back and the next page is last in the back stack) will focus the url bar while another action (e.g. forward if you pressed back) maybe be more appropriate

### What / Requirements
- A logical criteria for how the dpad should navigation through these views.

@aminalhazwani Can you go through the current implementation, see what feels wrong, and provide some criteria here? Thanks.

**Comment by aminalhazwani** [comment]
> Can you go through the current implementation, see what feels wrong, and provide some criteria here?

@mcomella thanks for reaching out! I actually wanted to ping you about the dpad navigation. We are in a tricky situation because we mix rows and grids elements in the same view. So we have two approaches here:

- First, we continue with the mixed model so things move in grid when focus is in a grid component and in rows when the focus is in a row component. Moving from rows to rows and from grid to rows should always focus the first _active_ item.

  - Pro: we keep the same navigation model for the pinned website
  - Cons: we mix two navigation models together

![homescreen default dpad navigation 1](https://user-images.githubusercontent.com/1721875/40012338-a818e068-57aa-11e8-94a5-9ff74c50bb05.jpg)

- Two, we keep just one navigation model, per rows, and when moving up and down we always focus the first _active_ item. 

  - Pro: we use one navigation model throughout the whole view
  - Cons: we introduce a new model for the pinned websites, rows navigation doesn't really belong to grid views

![homescreen default dpad navigation 2](https://user-images.githubusercontent.com/1721875/40012606-770fab18-57ab-11e8-9bcc-f38ef88824c7.jpg)

What are your thoughts?

**Comment by liuche** [comment]
I think the wraparound in 2 might be confusing esp since Pocket isn't part of the wraparound, so I'd prefer option 1.

**Comment by liuche** [comment]
Moving this to 3.0 because this is not changing the paradigm of "channel rows"

**Comment by psymoon** [comment]
@shorlander @antlam
> Selecting a button that is then disabled (e.g. press back and the next page is last in the back stack) will focus the url bar

is the current workflow. Any input on more appropriate solution?

**Comment by shorlander** [comment]
I think it might depend on the case, but in the example case I think that flow is fine. 

Once you get to the end of the stack selecting the next available navigation row puts you into a position to start a new task.

**Comment by aminalhazwani** [comment]
@psymoon I am back, what's the status? Thanks 👍
