### ISSUE TITLE
Pressing microphone button will pause the video, also resuming it needs to enter command twice

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#985]
### Steps to reproduce
- Go to youtube or any video site, play video
- Tap microphone button shortly, not saying anything

### Expected behavior
- Video should continue to play

### Actual behavior
- Video pauses

Then, say 'Alexa resume' or press mic button and say 'resume'
### Expected behavior
- Video should resume

### Actual behavior
- Video plays for a split second, then resumes

### Device information

* Fire TV device: Fire TV cube
* Firefox version: 2.2

-->

**Comment by mcomella** [comment]
@npark-mozilla When I click the microphone button briefly, there is an overlay on the screen, "Press and hold (mic) then speak after the tone." As the echo voice commands has focus for the user, rather than our app. To me, I wouldn't expect the video to keep playing if Amazon has focus (and in fact, I don't think we can do anything about it) so I think this is working as expected – would you agree?

**Comment by npark-mozilla** [comment]
@mcomella granted that pause after pressing the mic button is as expected, it's the next step that's a bit more strange.  It is paused after all, so 'resume' command should resume the video playback, but it re-pauses the video.  it may be a papercut bug, but it does feel odd to ask to resume video twice to get the video playing again.

**Comment by mcomella** [comment]
@npark-mozilla I think this should be fixed in the next LAT: it should have been fixed in #965.

I think we can close this as a dupe: should we leave this open for QA to verify? If not, please close!

**Comment by npark-mozilla** [comment]
verified it's fixed now in 2.2
