### ISSUE TITLE
UI Test won't launch with compile error on compileAmazonWebviewDebugAndroidTestKotlin

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#987]
### Steps to reproduce
UI Tests on AndroidTest folder won't start with compile error, but can't find in Android studio exactly what is missing.

* Fire TV device:  Simulator
* Firefox version: master

@liuche thanks for taking a look at this!

**Comment by liuche** [comment]
Long story short, there's a lot of changed resource ids - we majorly changed the layout of the app (we don't have a "home" button anymore) so most of these are compile-errors because the UI elements are different. I have a quick PR to fix some of these issues, but because we don't abstract things like "go to homescreen" vs "open menu overlay" it's not clear to me exactly what is being tested.

**Comment by npark-mozilla** [comment]
I see, strange that my android studio doesn't point out those compile errors in the failure list - if it's just matter of resource ids, that's a good news.

**Comment by liuche** [comment]
^ @npark-mozilla I added a quick PR that renames the urlbar input, but at the moment, I don't quite have the time to figure out when "menu-pressed" should be used vs "home button" so I left some stuff unfixed.
